#!/usr/bin/env bash
#
# tests/mcp_test.sh — exercise the `harness mcp` lifecycle without
# pulling Serena. We synthesize a tiny fake MCP entry under a tmpdir,
# point HARNESS_REGISTRY_DIR at it, and walk through enable / start /
# verify-network / disable / verify-removed.
#
# The fake MCP is `python:3.12-slim` running `python -m http.server`. It
# exposes nothing of substance; we use it purely to validate that:
#   - registry discovery finds it,
#   - enable copies it into the active tree,
#   - harness start brings it up on the harness-net network,
#   - the merged client config lands in the agent home,
#   - disable cleanly removes the active entry but preserves data/.
#
# Project name is fixed to harness-mcp-test so this never collides with a
# real harness instance running on the same daemon.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Cross-platform helpers (harness_docker, harness_docker_path).
# shellcheck source=lib/platform.sh
source "${REPO_ROOT}/scripts/lib/platform.sh"

PROJECT_NAME="harness-mcp-test"

echo "============================================================"
echo " harness MCP lifecycle test"
echo "============================================================"

# --- preflight --------------------------------------------------------------

if ! harness_docker info >/dev/null 2>&1; then
    echo "[mcp] ERROR: container runtime ($(harness_container_runtime)) not reachable" >&2
    exit 1
fi

# --- staging ----------------------------------------------------------------
#
# We build a self-contained "fake install root" mirroring the real layout
# the harness script expects. The registry override lets us inject our
# fake MCP without touching the real mcp-registry/ in the repo (which the
# user might want to ship to other people).

TEST_ROOT="$(mktemp -d -t harness-mcp-test.XXXXXX)"
FAKE_REGISTRY="${TEST_ROOT}/fake-registry"
FAKE_INSTALL_ROOT="${TEST_ROOT}/install-root"

mkdir -p "${FAKE_INSTALL_ROOT}" \
         "${FAKE_REGISTRY}/_test_mcp"

# Symlink the repo as <fake-install-root>/harness so the script's
# realpath/dirname walk lands in a sensible place. HARNESS_INSTALL_ROOT
# pins it explicitly anyway, but the symlink lets `harness` exist on the
# expected path.
ln -s "${REPO_ROOT}" "${FAKE_INSTALL_ROOT}/harness"

cleanup() {
    local rc=$?
    echo "[mcp] cleanup (rc=${rc})"

    if [[ -x "${FAKE_INSTALL_ROOT}/harness/harness" ]]; then
        HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
        HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
        HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}" \
            "${FAKE_INSTALL_ROOT}/harness/harness" down >/dev/null 2>&1 || true
    fi
    harness_docker compose --project-name "${PROJECT_NAME}" \
        -f "${REPO_ROOT}/docker-compose.yml" \
        down -v --remove-orphans >/dev/null 2>&1 || true

    if [[ -d "${TEST_ROOT}" ]]; then
        if ! rm -rf "${TEST_ROOT}" 2>/dev/null; then
            harness_docker run --rm -v "$(harness_docker_path "${TEST_ROOT}"):/target" --user 0:0 alpine \
                sh -c 'rm -rf /target/* /target/.[!.]* 2>/dev/null || true' \
                >/dev/null 2>&1 || true
            rm -rf "${TEST_ROOT}" 2>/dev/null || true
        fi
    fi
    exit "${rc}"
}
trap cleanup EXIT INT TERM

cat >"${FAKE_INSTALL_ROOT}/.env" <<'EOF'
PROXY_API_URL=http://placeholder.invalid/v1/chat/completions
PROXY_API_KEY=test-key-1234
DEFAULT_MODEL_NAME=harness
PROXY_HOST=0.0.0.0
PROXY_PORT=8000
OUTPUT_DIR=
PROXY_TIMEOUT=30
MODEL_CONTEXT_LENGTH=200000
EOF

# Firewall allowlist. The .env above points PROXY_API_URL at
# placeholder.invalid, which the proxy entrypoint guardrail validates
# against this list, so include it explicitly.
ALLOWLIST_FILE="${FAKE_INSTALL_ROOT}/.harness-allowlist"
cat >"${ALLOWLIST_FILE}" <<'EOF'
# auto-generated by mcp_test.sh
github.com
api.github.com
codeload.github.com
raw.githubusercontent.com
objects.githubusercontent.com
pypi.org
files.pythonhosted.org
registry.npmjs.org
placeholder.invalid
EOF
# Convert host path for Docker Desktop's WSL2 backend (Windows). On Linux
# this is a passthrough; on Windows /tmp/... and /c/... are rewritten to
# C:/... so the bind mount actually exposes the file inside the container.
export HARNESS_ALLOWLIST_PATH="$(harness_docker_path "${ALLOWLIST_FILE}")"

# --- fake MCP fixture -------------------------------------------------------
#
# compose.yml: lightweight HTTP service. Network is declared with the
# matching short name as the main compose file (no external/no name) so
# compose merges them into a single project-namespaced network. This is
# the same shape the production Serena fixture uses.

cat >"${FAKE_REGISTRY}/_test_mcp/compose.yml" <<'EOF'
services:
  test_mcp:
    image: python:3.12-slim
    container_name: harness-mcp-test_test_mcp
    networks:
      - harness-net
    profiles:
      - mcp
    command: python -m http.server 8765 --bind 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://127.0.0.1:8765/\",timeout=2).status==200 else 1)'"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s
networks:
  harness-net:
EOF

cat >"${FAKE_REGISTRY}/_test_mcp/client-config.json" <<'EOF'
{
  "mcpServers": {
    "test_mcp": {
      "type": "sse",
      "url": "http://test_mcp:8765/sse"
    }
  }
}
EOF

cat >"${FAKE_REGISTRY}/_test_mcp/README.md" <<'EOF'
# _test_mcp — fixture used by tests/mcp_test.sh.
EOF

# Sanity: also register a "non-test" entry so we can verify list filtering.
mkdir -p "${FAKE_REGISTRY}/dummy"
cat >"${FAKE_REGISTRY}/dummy/compose.yml" <<'EOF'
services:
  dummy:
    image: alpine:latest
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
cat >"${FAKE_REGISTRY}/dummy/client-config.json" <<'EOF'
{ "mcpServers": { "dummy": { "type": "sse", "url": "http://dummy:1/" } } }
EOF

# --- helper -----------------------------------------------------------------

harness_call() {
    HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
    HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
    HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}" \
        "${FAKE_INSTALL_ROOT}/harness/harness" "$@"
}

# Defensive: clear any stragglers from a prior run.
harness_docker compose --project-name "${PROJECT_NAME}" \
    -f "${REPO_ROOT}/docker-compose.yml" \
    down -v --remove-orphans >/dev/null 2>&1 || true

# --- T1: list shows registry entries, none installed -----------------------

echo "[mcp] T1: harness mcp list — registry only, none installed"
# Plain 'mcp list' shows only installed entries (Phase 13b); use --available
# to surface registry entries that haven't been installed yet.
plain_out=$(harness_call mcp list)
echo "${plain_out}" | sed 's/^/  | (plain) /'
if ! grep -qi 'no MCPs installed' <<<"${plain_out}"; then
    echo "[mcp] T1 FAIL: plain 'mcp list' with nothing installed should say so" >&2
    exit 1
fi
list_out=$(harness_call mcp list --available)
echo "${list_out}" | sed 's/^/  | /'
# `_test_mcp` should be hidden (underscore-prefixed test fixtures don't
# show in user-facing list). `dummy` should appear with state=available.
if ! grep -Eq 'dummy[[:space:]]+available' <<<"${list_out}"; then
    echo "[mcp] T1 FAIL: dummy should be listed with state=available" >&2
    exit 1
fi
if grep -q '_test_mcp' <<<"${list_out}"; then
    echo "[mcp] T1 FAIL: _test_mcp should be hidden from list (underscore-prefixed)" >&2
    exit 1
fi
echo "[mcp] T1 OK"

# --- T2: install unknown errors with the available list -------------------

echo "[mcp] T2: harness mcp install nope (unknown name)"
set +e
err_out=$(harness_call mcp install nope 2>&1)
err_rc=$?
set -e
if (( err_rc == 0 )); then
    echo "[mcp] T2 FAIL: install nope unexpectedly succeeded" >&2
    exit 1
fi
if ! grep -qi 'unknown MCP' <<<"${err_out}"; then
    echo "[mcp] T2 FAIL: error doesn't mention 'unknown MCP': ${err_out}" >&2
    exit 1
fi
echo "[mcp] T2 OK"

# --- T3: install copies entry into active tree + writes harness-meta.json -

echo "[mcp] T3: harness mcp install _test_mcp"
harness_call mcp install _test_mcp >"${TEST_ROOT}/install.log" 2>&1
echo "  | $(grep -E '^(installed|state)' "${TEST_ROOT}/install.log" || true)"

if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T3 FAIL: compose.yml not copied" >&2
    cat "${TEST_ROOT}/install.log" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/client-config.json" ]]; then
    echo "[mcp] T3 FAIL: client-config.json not copied" >&2
    exit 1
fi
if [[ ! -d "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/data" ]]; then
    echo "[mcp] T3 FAIL: data/ not pre-created" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json" ]]; then
    echo "[mcp] T3 FAIL: harness-meta.json not written on install" >&2
    exit 1
fi
echo "[mcp] T3 OK"

# --- T4: re-install without --force fails ----------------------------------

echo "[mcp] T4: re-install without --force fails"
set +e
re_out=$(harness_call mcp install _test_mcp 2>&1)
re_rc=$?
set -e
if (( re_rc == 0 )); then
    echo "[mcp] T4 FAIL: re-install succeeded without --force" >&2
    echo "${re_out}" >&2
    exit 1
fi
echo "[mcp] T4 OK (rc=${re_rc})"

# --- T5: harness start brings up the fake MCP -------------------------------

echo "[mcp] T5: harness start with active MCP"
harness_call start >"${TEST_ROOT}/start.log" 2>&1 || {
    echo "[mcp] T5 FAIL: start exited non-zero" >&2
    tail -50 "${TEST_ROOT}/start.log" >&2
    exit 1
}

# Wait for the fake MCP container to become healthy (its compose file has
# a healthcheck; 60s ceiling).
deadline=$(( $(date +%s) + 60 ))
mcp_cid=""
while true; do
    mcp_cid=$(harness_docker compose --project-name "${PROJECT_NAME}" \
        -f "${REPO_ROOT}/docker-compose.yml" \
        -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" \
        ps -q test_mcp 2>/dev/null || true)
    if [[ -n "${mcp_cid}" ]]; then
        status=$(harness_docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${mcp_cid}" 2>/dev/null || echo "none")
        if [[ "${status}" == "healthy" ]]; then
            break
        fi
    fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T5 FAIL: test_mcp not healthy in 60s" >&2
        harness_docker compose --project-name "${PROJECT_NAME}" \
            -f "${REPO_ROOT}/docker-compose.yml" \
            -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ps >&2 || true
        harness_docker logs "${mcp_cid}" 2>&1 | tail -30 >&2 || true
        exit 1
    fi
    sleep 2
done
echo "[mcp] T5 OK"

# --- T6: list now shows _test_mcp as enabled + running ---------------------
#
# (Listing matches by underscore-prefix; from T1 we know it's hidden in
# user-facing output. So we instead verify via `mcp list` that the active
# entry is reflected in the running state — the fact that T5 succeeded
# already proves the active tree was discovered.)

# Verify any-mcp-active branch ran by checking that the start log invoked
# --profile mcp. We emit it via compose's verbose output indirectly — the
# easiest signal is that the test_mcp container is up.
echo "[mcp] T6: services up after start"
proxy_cid=$(harness_docker compose --project-name "${PROJECT_NAME}" \
    -f "${REPO_ROOT}/docker-compose.yml" \
    -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" \
    ps -q proxy 2>/dev/null || true)
if [[ -z "${proxy_cid}" ]]; then
    echo "[mcp] T6 FAIL: proxy container not present (unrelated regression?)" >&2
    exit 1
fi
echo "[mcp] T6 OK"

# --- T7: agent client config gets the merged entry -------------------------
#
# The MCP side file is produced by write_agent_mcp_config, which run_agent
# calls *before* the on-demand image build (write_agent_mcp_config precedes
# run_agent's `image inspect` / `compose build agent` block). Observing it
# via `harness opencode` would auto-build the multi-GB agent image — a build
# that never even touches the file. So we call write_agent_mcp_config
# directly: source harness with HARNESS_SOURCE_ONLY=1 (its documented test
# seam — main is skipped) inside a subshell so its helpers don't leak into
# this script, with the same env the real launch resolves paths from.
# The real launch ordering is covered separately by full_pipeline_test.sh.
echo "[mcp] T7: merged client config side file"
(
    export HARNESS_SOURCE_ONLY=1
    export HARNESS_PROJECT_NAME="${PROJECT_NAME}"
    export HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}"
    export HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}"
    # shellcheck disable=SC1091
    source "${FAKE_INSTALL_ROOT}/harness/harness"
    write_agent_mcp_config
)

side_file="${FAKE_INSTALL_ROOT}/state/agent/home/.harness-mcp-servers.json"
if [[ ! -f "${side_file}" ]]; then
    echo "[mcp] T7 FAIL: ${side_file} not written" >&2
    exit 1
fi
if ! grep -q 'test_mcp' "${side_file}"; then
    echo "[mcp] T7 FAIL: side file does not mention test_mcp" >&2
    cat "${side_file}" >&2
    exit 1
fi
if ! grep -q '"http://test_mcp:8765/sse"' "${side_file}"; then
    echo "[mcp] T7 FAIL: side file missing the test_mcp url" >&2
    cat "${side_file}" >&2
    exit 1
fi
echo "[mcp] T7 OK"

# --- T8: mcp status reports installed-enabled ------------------------------

echo "[mcp] T8: harness mcp status _test_mcp"
status_out=$(harness_call mcp status _test_mcp)
echo "${status_out}" | sed 's/^/  | /'
if ! grep -Eq '^state:[[:space:]]+installed-enabled' <<<"${status_out}"; then
    echo "[mcp] T8 FAIL: status missing 'state: installed-enabled'" >&2
    exit 1
fi
if ! grep -Eq '^enabled:[[:space:]]+true' <<<"${status_out}"; then
    echo "[mcp] T8 FAIL: status missing 'enabled: true'" >&2
    exit 1
fi
if ! grep -Eq '^services:[[:space:]]+test_mcp' <<<"${status_out}"; then
    echo "[mcp] T8 FAIL: status missing services list" >&2
    exit 1
fi
echo "[mcp] T8 OK"

# --- T9: state-flag disable (no --force) keeps files, flips enabled --------

echo "[mcp] T9: harness mcp disable _test_mcp (state toggle, no --force)"
disable_out=$(harness_call mcp disable _test_mcp 2>&1)
echo "${disable_out}" | sed 's/^/  | /'
if ! grep -q "^disabled: _test_mcp" <<<"${disable_out}"; then
    echo "[mcp] T9 FAIL: expected 'disabled: _test_mcp' message" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T9 FAIL: compose.yml unexpectedly removed by state-flag disable" >&2
    exit 1
fi
if ! grep -q '"enabled": false' "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json"; then
    echo "[mcp] T9 FAIL: harness-meta.json should report enabled=false" >&2
    cat "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json" >&2
    exit 1
fi
# status should now say installed-disabled.
# Capture first then grep — under `set -euo pipefail`, piping a multi-line
# producer into `grep -q` causes SIGPIPE on the producer (rc=141), which
# pipefail elevates to the pipeline rc, and `if !` flips that to truthy.
status_t9_out=$(harness_call mcp status _test_mcp)
if ! grep -Eq '^state:[[:space:]]+installed-disabled' <<<"${status_t9_out}"; then
    echo "[mcp] T9 FAIL: status should report installed-disabled" >&2
    echo "${status_t9_out}" >&2
    exit 1
fi
echo "[mcp] T9 OK"

# --- T10: post-disable start drops the MCP service -------------------------

echo "[mcp] T10: post-disable start drops the MCP service"
harness_call start >"${TEST_ROOT}/start2.log" 2>&1 || {
    echo "[mcp] T10 FAIL: start exited non-zero after state-flag disable" >&2
    tail -30 "${TEST_ROOT}/start2.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 30 ))
while true; do
    cid=$(harness_docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -z "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T10 FAIL: test_mcp container still running after state-flag disable" >&2
        exit 1
    fi
    sleep 2
done
echo "[mcp] T10 OK"

# --- T11: mcp up brings a disabled MCP back up manually --------------------

echo "[mcp] T11: harness mcp up _test_mcp (manual control of disabled MCP)"
harness_call mcp up _test_mcp >"${TEST_ROOT}/up.log" 2>&1 || {
    echo "[mcp] T11 FAIL: mcp up exited non-zero" >&2
    tail -30 "${TEST_ROOT}/up.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 60 ))
while true; do
    cid=$(harness_docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -n "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T11 FAIL: mcp up did not start the container" >&2
        cat "${TEST_ROOT}/up.log" >&2
        exit 1
    fi
    sleep 2
done
# Even though container is up, enabled flag should still be false (mcp up
# does not flip it).
if ! grep -q '"enabled": false' "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json"; then
    echo "[mcp] T11 FAIL: 'mcp up' must not flip enabled flag" >&2
    exit 1
fi
echo "[mcp] T11 OK"

# --- T12: mcp down stops the container without changing enabled flag -------

echo "[mcp] T12: harness mcp down _test_mcp"
harness_call mcp down _test_mcp >"${TEST_ROOT}/down.log" 2>&1 || {
    echo "[mcp] T12 FAIL: mcp down exited non-zero" >&2
    tail -30 "${TEST_ROOT}/down.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 30 ))
while true; do
    cid=$(harness_docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -z "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T12 FAIL: mcp down did not stop the container" >&2
        exit 1
    fi
    sleep 2
done
echo "[mcp] T12 OK"

# --- T13: mcp enable (state toggle) restores auto-start --------------------

echo "[mcp] T13: harness mcp enable _test_mcp (state toggle restore)"
enable_out=$(harness_call mcp enable _test_mcp 2>&1)
echo "${enable_out}" | sed 's/^/  | /'
if ! grep -q "^enabled: _test_mcp" <<<"${enable_out}"; then
    echo "[mcp] T13 FAIL: expected 'enabled: _test_mcp' message" >&2
    exit 1
fi
if ! grep -q '"enabled": true' "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json"; then
    echo "[mcp] T13 FAIL: harness-meta.json should report enabled=true" >&2
    exit 1
fi
echo "[mcp] T13 OK"

# --- T14: harness mcp uninstall removes config but preserves data ----------

echo "[mcp] T14: harness mcp uninstall _test_mcp --force"
# Drop a marker into data/ so we can prove preservation.
echo "data marker" >"${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/data/marker.txt"

harness_call mcp uninstall _test_mcp --force >"${TEST_ROOT}/uninstall.log" 2>&1
echo "  | $(grep -E '^uninstalled|^data preserved' "${TEST_ROOT}/uninstall.log" || true)"

if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T14 FAIL: compose.yml still present after uninstall" >&2
    exit 1
fi
if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json" ]]; then
    echo "[mcp] T14 FAIL: harness-meta.json still present after uninstall" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/data/marker.txt" ]]; then
    echo "[mcp] T14 FAIL: data/marker.txt was removed by uninstall" >&2
    exit 1
fi
echo "[mcp] T14 OK"

# --- T15: --force on disable is rejected (canonical state-flag command) ----
#
# After Phase 13b enable/disable became canonical state-flag commands and
# the --force alias was removed. Verify disable rejects unknown flags
# rather than forwarding to uninstall.

echo "[mcp] T15: 'mcp disable --force' is rejected (no longer an uninstall alias)"
harness_call mcp install _test_mcp >/dev/null 2>&1
set +e
no_force_out=$(harness_call mcp disable _test_mcp --force 2>&1)
no_force_rc=$?
set -e
echo "${no_force_out}" | sed 's/^/  | /'
if (( no_force_rc == 0 )); then
    echo "[mcp] T15 FAIL: disable --force should be rejected" >&2
    exit 1
fi
if ! grep -qiE "unknown flag" <<<"${no_force_out}"; then
    echo "[mcp] T15 FAIL: rejection should mention 'unknown flag'" >&2
    exit 1
fi
# Files should still be there (disable was rejected).
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T15 FAIL: rejected disable still removed files" >&2
    exit 1
fi
# Clean up: uninstall properly so T16 sees a clean state.
harness_call mcp uninstall _test_mcp --force >/dev/null 2>&1
echo "[mcp] T15 OK"

# --- T16: re-running harness start no longer brings up the MCP -------------

echo "[mcp] T16: post-uninstall start drops the MCP service"
harness_call start >"${TEST_ROOT}/start3.log" 2>&1 || {
    echo "[mcp] T16 FAIL: start exited non-zero after uninstall" >&2
    tail -30 "${TEST_ROOT}/start3.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 30 ))
while true; do
    cid=$(harness_docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -z "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T16 FAIL: test_mcp container still running after uninstall" >&2
        exit 1
    fi
    sleep 2
done
echo "[mcp] T16 OK"

# --- T17: agent side file is cleaned on next launch ------------------------

echo "[mcp] T17: side file disappears when no MCPs are active"
# Re-run the side-file write path now that T16 has uninstalled _test_mcp:
# with zero enabled entries, write_agent_mcp_config removes the stale side
# file. Direct call via the source seam — same rationale as T7 (no build).
(
    export HARNESS_SOURCE_ONLY=1
    export HARNESS_PROJECT_NAME="${PROJECT_NAME}"
    export HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}"
    export HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}"
    # shellcheck disable=SC1091
    source "${FAKE_INSTALL_ROOT}/harness/harness"
    write_agent_mcp_config
)

if [[ -f "${side_file}" ]]; then
    echo "[mcp] T17 FAIL: stale side file should have been removed: ${side_file}" >&2
    cat "${side_file}" >&2
    exit 1
fi
echo "[mcp] T17 OK"

# --- T18: install prints allowed_domains recommendations ---------------------
#
# Add a fixture MCP whose harness-meta.json.template lists allowed_domains.
# `harness mcp install` should PRINT the recommendation but NOT auto-modify
# the allowlist (we then assert the allowlist is unchanged).

echo "[mcp] T18: install prints allowed_domains recommendations"
DOMAINS_REG="${TEST_ROOT}/dom-registry"
mkdir -p "${DOMAINS_REG}/dom_test"
cat >"${DOMAINS_REG}/dom_test/compose.yml" <<'EOF'
services:
  dom_test:
    image: alpine:latest
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
cat >"${DOMAINS_REG}/dom_test/client-config.json" <<'EOF'
{ "mcpServers": { "dom_test": { "type": "sse", "url": "http://dom_test:1/" } } }
EOF
cat >"${DOMAINS_REG}/dom_test/harness-meta.json.template" <<'EOF'
{
  "enabled": true,
  "allowed_domains": [
    "example.com",
    "another.example.org"
  ]
}
EOF

# Snapshot allowlist before so we can prove the recommendation is print-only.
cp "${ALLOWLIST_FILE}" "${ALLOWLIST_FILE}.before-t18"

set +e
dom_out=$(HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
    HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
    HARNESS_REGISTRY_DIR="${DOMAINS_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp install dom_test 2>&1)
dom_rc=$?
set -e
echo "${dom_out}" | sed 's/^/  | /'
if (( dom_rc != 0 )); then
    echo "[mcp] T18 FAIL: install dom_test exited ${dom_rc}" >&2
    exit 1
fi
if ! grep -q 'recommends allowlisting' <<<"${dom_out}"; then
    echo "[mcp] T18 FAIL: install did not print allowed_domains recommendation" >&2
    exit 1
fi
for d in example.com another.example.org; do
    if ! grep -Eq "harness net allow ${d}" <<<"${dom_out}"; then
        echo "[mcp] T18 FAIL: install did not suggest 'harness net allow ${d}'" >&2
        exit 1
    fi
done
# Confirm it did NOT auto-modify the allowlist.
if ! diff -q "${ALLOWLIST_FILE}.before-t18" "${ALLOWLIST_FILE}" >/dev/null; then
    echo "[mcp] T18 FAIL: allowlist was modified by install (must only print)" >&2
    diff -u "${ALLOWLIST_FILE}.before-t18" "${ALLOWLIST_FILE}" >&2 || true
    exit 1
fi
# Cleanup.
HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
HARNESS_REGISTRY_DIR="${DOMAINS_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp uninstall dom_test --force >/dev/null 2>&1 || true
rm -f "${ALLOWLIST_FILE}.before-t18"
echo "[mcp] T18 OK"

# --- T19: empty/no allowed_domains => no recommendation block ---------------
#
# An MCP with empty allowed_domains (the Serena default in B2) must NOT
# print the recommendations section. Same as T18 but with [] in the template.

echo "[mcp] T19: empty allowed_domains prints nothing"
EMPTY_REG="${TEST_ROOT}/empty-domains-registry"
mkdir -p "${EMPTY_REG}/empty_dom"
cat >"${EMPTY_REG}/empty_dom/compose.yml" <<'EOF'
services:
  empty_dom:
    image: alpine:latest
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
cat >"${EMPTY_REG}/empty_dom/client-config.json" <<'EOF'
{ "mcpServers": { "empty_dom": { "type": "sse", "url": "http://empty_dom:1/" } } }
EOF
cat >"${EMPTY_REG}/empty_dom/harness-meta.json.template" <<'EOF'
{
  "enabled": true,
  "allowed_domains": []
}
EOF

set +e
empty_out=$(HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
    HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
    HARNESS_REGISTRY_DIR="${EMPTY_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp install empty_dom 2>&1)
set -e
if grep -q 'recommends allowlisting' <<<"${empty_out}"; then
    echo "[mcp] T19 FAIL: install printed allowed_domains block for empty array" >&2
    echo "${empty_out}" >&2
    exit 1
fi
HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
HARNESS_REGISTRY_DIR="${EMPTY_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp uninstall empty_dom --force >/dev/null 2>&1 || true
echo "[mcp] T19 OK"

# ===========================================================================
# Register (TR-series) — `harness mcp register` dynamic registration.
#
# register lands an arbitrary external source (a registry-shaped dir or a git
# URL) into the active tree behind a compose-merge validation gate, WITHOUT a
# repo commit. These are docker-tier (the gate runs `docker compose config`
# over the full graph), so CI exercises them; the docker-free check is bash -n.
# See .planning/proposals/mcp-register.md and architecture/mcp.md.
# ===========================================================================

# A minimal valid registry-shaped source dir: one alpine 'sleep' service behind
# the mcp profile on harness-net, plus the required client-config.json. No
# harness-meta — register synthesizes one (enabled flag) on materialize.
make_reg_src() {
    local dir="$1" svc="$2"
    local cname="${3:-harness-mcp-test_${svc}}"
    mkdir -p "${dir}"
    cat >"${dir}/compose.yml" <<EOF
services:
  ${svc}:
    image: alpine:latest
    container_name: ${cname}
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
    cat >"${dir}/client-config.json" <<EOF
{ "mcpServers": { "${svc}": { "type": "sse", "url": "http://${svc}:8765/sse" } } }
EOF
}

# Source seam: run a harness function with HARNESS_SOURCE_ONLY=1 (main skipped)
# under the test env, echoing its output. Used to observe mcp_compose_files and
# write_agent_mcp_config without launching anything (mirrors T7's approach).
seam_mcp_compose_files() {
    (
        export HARNESS_SOURCE_ONLY=1
        export HARNESS_PROJECT_NAME="${PROJECT_NAME}"
        export HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}"
        export HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}"
        # shellcheck disable=SC1091
        source "${FAKE_INSTALL_ROOT}/harness/harness"
        mcp_compose_files
    )
}
seam_write_agent_mcp_config() {
    (
        export HARNESS_SOURCE_ONLY=1
        export HARNESS_PROJECT_NAME="${PROJECT_NAME}"
        export HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}"
        export HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}"
        # shellcheck disable=SC1091
        source "${FAKE_INSTALL_ROOT}/harness/harness"
        write_agent_mcp_config
    )
}

# --- TR1: register from a valid dir materializes the active tree ------------

echo "[mcp] TR1: register <name> --from <valid-dir>"
make_reg_src "${TEST_ROOT}/src-reg1" reg1
harness_call mcp register reg1 --from "${TEST_ROOT}/src-reg1" >"${TEST_ROOT}/reg1.log" 2>&1 || {
    echo "[mcp] TR1 FAIL: register exited non-zero" >&2
    cat "${TEST_ROOT}/reg1.log" >&2
    exit 1
}
for f in compose.yml client-config.json harness-meta.json; do
    if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/reg1/${f}" ]]; then
        echo "[mcp] TR1 FAIL: ${f} not materialized" >&2
        cat "${TEST_ROOT}/reg1.log" >&2
        exit 1
    fi
done
if [[ ! -d "${FAKE_INSTALL_ROOT}/state/mcp/reg1/data" ]]; then
    echo "[mcp] TR1 FAIL: data/ not created" >&2
    exit 1
fi
if ! grep -q '"enabled": true' "${FAKE_INSTALL_ROOT}/state/mcp/reg1/harness-meta.json"; then
    echo "[mcp] TR1 FAIL: harness-meta.json should report enabled=true" >&2
    cat "${FAKE_INSTALL_ROOT}/state/mcp/reg1/harness-meta.json" >&2
    exit 1
fi
# The hidden staging dir must not linger after a successful register.
if [[ -e "${FAKE_INSTALL_ROOT}/state/mcp/.staging-reg1" ]]; then
    echo "[mcp] TR1 FAIL: staging dir left behind" >&2
    exit 1
fi
echo "[mcp] TR1 OK"

# --- TR2: malformed compose is rejected; staging discarded -----------------

echo "[mcp] TR2: register with malformed compose is rejected"
mkdir -p "${TEST_ROOT}/src-reg2"
cat >"${TEST_ROOT}/src-reg2/compose.yml" <<'EOF'
services:
  reg2:
    image: alpine:latest
    networks: [harness-net
    profiles: [mcp]
EOF
cat >"${TEST_ROOT}/src-reg2/client-config.json" <<'EOF'
{ "mcpServers": { "reg2": { "type": "sse", "url": "http://reg2:1/" } } }
EOF
set +e
reg2_out=$(harness_call mcp register reg2 --from "${TEST_ROOT}/src-reg2" 2>&1)
reg2_rc=$?
set -e
echo "${reg2_out}" | sed 's/^/  | /'
if (( reg2_rc == 0 )); then
    echo "[mcp] TR2 FAIL: register accepted a malformed compose" >&2
    exit 1
fi
if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/reg2/compose.yml" ]]; then
    echo "[mcp] TR2 FAIL: malformed register left an active entry" >&2
    exit 1
fi
if [[ -e "${FAKE_INSTALL_ROOT}/state/mcp/.staging-reg2" ]]; then
    echo "[mcp] TR2 FAIL: staging dir not discarded after failure" >&2
    exit 1
fi
echo "[mcp] TR2 OK"

# --- TR3: service-name collision is rejected -------------------------------

echo "[mcp] TR3: register colliding service name (proxy) is rejected"
make_reg_src "${TEST_ROOT}/src-reg3" proxy harness-mcp-test_reg3svc
set +e
reg3_out=$(harness_call mcp register reg3 --from "${TEST_ROOT}/src-reg3" 2>&1)
reg3_rc=$?
set -e
echo "${reg3_out}" | sed 's/^/  | /'
if (( reg3_rc == 0 )); then
    echo "[mcp] TR3 FAIL: register accepted a service-name collision" >&2
    exit 1
fi
if ! grep -qi 'redefines service' <<<"${reg3_out}"; then
    echo "[mcp] TR3 FAIL: rejection should mention the service collision" >&2
    exit 1
fi
if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/reg3/compose.yml" ]]; then
    echo "[mcp] TR3 FAIL: collision register left an active entry" >&2
    exit 1
fi
echo "[mcp] TR3 OK"

# --- TR4: --no-enable lands disabled; excluded from start until enabled ----

echo "[mcp] TR4: register --no-enable lands disabled, excluded from compose files"
make_reg_src "${TEST_ROOT}/src-reg4" reg4
harness_call mcp register reg4 --from "${TEST_ROOT}/src-reg4" --no-enable >"${TEST_ROOT}/reg4.log" 2>&1 || {
    echo "[mcp] TR4 FAIL: register --no-enable exited non-zero" >&2
    cat "${TEST_ROOT}/reg4.log" >&2
    exit 1
}
if ! grep -q '"enabled": false' "${FAKE_INSTALL_ROOT}/state/mcp/reg4/harness-meta.json"; then
    echo "[mcp] TR4 FAIL: --no-enable should land enabled=false" >&2
    exit 1
fi
# Disabled => excluded from the enabled-only enumeration `harness start` reads.
cf_pre=$(seam_mcp_compose_files)
if grep -q 'mcp/reg4' <<<"${cf_pre}"; then
    echo "[mcp] TR4 FAIL: disabled reg4 should not appear in mcp_compose_files" >&2
    echo "${cf_pre}" >&2
    exit 1
fi
# Enable flips it in.
harness_call mcp enable reg4 >/dev/null 2>&1
if ! grep -q '"enabled": true' "${FAKE_INSTALL_ROOT}/state/mcp/reg4/harness-meta.json"; then
    echo "[mcp] TR4 FAIL: enable should flip reg4 to enabled=true" >&2
    exit 1
fi
cf_post=$(seam_mcp_compose_files)
if ! grep -q 'mcp/reg4' <<<"${cf_post}"; then
    echo "[mcp] TR4 FAIL: enabled reg4 should appear in mcp_compose_files" >&2
    echo "${cf_post}" >&2
    exit 1
fi
echo "[mcp] TR4 OK"

# --- TR5: enabled registered MCP reaches compose files + side file ---------

echo "[mcp] TR5: enabled registered MCP in mcp_compose_files + .harness-mcp-servers.json"
make_reg_src "${TEST_ROOT}/src-reg5" reg5
harness_call mcp register reg5 --from "${TEST_ROOT}/src-reg5" >"${TEST_ROOT}/reg5.log" 2>&1 || {
    echo "[mcp] TR5 FAIL: register exited non-zero" >&2
    cat "${TEST_ROOT}/reg5.log" >&2
    exit 1
}
cf5=$(seam_mcp_compose_files)
if ! grep -q 'mcp/reg5' <<<"${cf5}"; then
    echo "[mcp] TR5 FAIL: reg5 not in mcp_compose_files" >&2
    echo "${cf5}" >&2
    exit 1
fi
seam_write_agent_mcp_config
if ! grep -q '"http://reg5:8765/sse"' "${side_file}"; then
    echo "[mcp] TR5 FAIL: side file missing reg5 url" >&2
    cat "${side_file}" >&2
    exit 1
fi
echo "[mcp] TR5 OK"

# --- TR6: refuse already-installed without --force; --force keeps data/ ----

echo "[mcp] TR6: register refuses an installed name without --force; --force preserves data/"
make_reg_src "${TEST_ROOT}/src-reg6" reg6
harness_call mcp register reg6 --from "${TEST_ROOT}/src-reg6" >/dev/null 2>&1 || {
    echo "[mcp] TR6 FAIL: initial register exited non-zero" >&2
    exit 1
}
echo "reg6 marker" >"${FAKE_INSTALL_ROOT}/state/mcp/reg6/data/marker.txt"
set +e
reg6_out=$(harness_call mcp register reg6 --from "${TEST_ROOT}/src-reg6" 2>&1)
reg6_rc=$?
set -e
if (( reg6_rc == 0 )); then
    echo "[mcp] TR6 FAIL: re-register without --force should fail" >&2
    exit 1
fi
if ! grep -qi 'already installed' <<<"${reg6_out}"; then
    echo "[mcp] TR6 FAIL: rejection should mention 'already installed'" >&2
    echo "${reg6_out}" >&2
    exit 1
fi
harness_call mcp register reg6 --from "${TEST_ROOT}/src-reg6" --force >/dev/null 2>&1 || {
    echo "[mcp] TR6 FAIL: --force re-register exited non-zero" >&2
    exit 1
}
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/reg6/data/marker.txt" ]]; then
    echo "[mcp] TR6 FAIL: --force re-register destroyed data/" >&2
    exit 1
fi
echo "[mcp] TR6 OK"

# --- TR7: prints allowed_domains recs; allowlist unchanged (mirrors T18) ---

echo "[mcp] TR7: register prints allowed_domains recommendations, allowlist unchanged"
make_reg_src "${TEST_ROOT}/src-reg7" reg7
cat >"${TEST_ROOT}/src-reg7/harness-meta.json.template" <<'EOF'
{
  "enabled": true,
  "allowed_domains": [
    "example.com",
    "another.example.org"
  ]
}
EOF
cp "${ALLOWLIST_FILE}" "${ALLOWLIST_FILE}.before-tr7"
set +e
reg7_out=$(harness_call mcp register reg7 --from "${TEST_ROOT}/src-reg7" 2>&1)
reg7_rc=$?
set -e
echo "${reg7_out}" | sed 's/^/  | /'
if (( reg7_rc != 0 )); then
    echo "[mcp] TR7 FAIL: register exited ${reg7_rc}" >&2
    exit 1
fi
if ! grep -q 'recommends allowlisting' <<<"${reg7_out}"; then
    echo "[mcp] TR7 FAIL: register did not print allowed_domains recommendation" >&2
    exit 1
fi
for d in example.com another.example.org; do
    if ! grep -Eq "harness net allow ${d}" <<<"${reg7_out}"; then
        echo "[mcp] TR7 FAIL: register did not suggest 'harness net allow ${d}'" >&2
        exit 1
    fi
done
if ! diff -q "${ALLOWLIST_FILE}.before-tr7" "${ALLOWLIST_FILE}" >/dev/null; then
    echo "[mcp] TR7 FAIL: register modified the allowlist (must only print)" >&2
    diff -u "${ALLOWLIST_FILE}.before-tr7" "${ALLOWLIST_FILE}" >&2 || true
    exit 1
fi
rm -f "${ALLOWLIST_FILE}.before-tr7"
echo "[mcp] TR7 OK"

# --- TR8: uninstall a registered MCP preserves data/ (inverse of register) -

echo "[mcp] TR8: uninstall a registered MCP preserves data/"
make_reg_src "${TEST_ROOT}/src-reg8" reg8
harness_call mcp register reg8 --from "${TEST_ROOT}/src-reg8" >/dev/null 2>&1 || {
    echo "[mcp] TR8 FAIL: register exited non-zero" >&2
    exit 1
}
echo "reg8 marker" >"${FAKE_INSTALL_ROOT}/state/mcp/reg8/data/marker.txt"
harness_call mcp uninstall reg8 --force >"${TEST_ROOT}/reg8-uninstall.log" 2>&1
if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/reg8/compose.yml" ]]; then
    echo "[mcp] TR8 FAIL: compose.yml present after uninstall" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/reg8/data/marker.txt" ]]; then
    echo "[mcp] TR8 FAIL: data/marker.txt removed by uninstall" >&2
    exit 1
fi
echo "[mcp] TR8 OK"

# --- TR9: registering a name that shadows a registry entry warns -----------

echo "[mcp] TR9: register a name that shadows a registry entry warns"
make_reg_src "${TEST_ROOT}/src-reg9" shadowsvc
# 'dummy' exists in FAKE_REGISTRY (created during staging) — registering under
# that name must warn that `harness upgrade` would later overwrite it.
set +e
reg9_out=$(harness_call mcp register dummy --from "${TEST_ROOT}/src-reg9" 2>&1)
reg9_rc=$?
set -e
echo "${reg9_out}" | sed 's/^/  | /'
if (( reg9_rc != 0 )); then
    echo "[mcp] TR9 FAIL: register dummy exited ${reg9_rc}" >&2
    exit 1
fi
if ! grep -qi 'also names a registry entry' <<<"${reg9_out}"; then
    echo "[mcp] TR9 FAIL: register did not print the shadow warning" >&2
    exit 1
fi
harness_call mcp uninstall dummy --force >/dev/null 2>&1 || true
echo "[mcp] TR9 OK"

# --- TR10: register from a git URL clones repo/ at the pinned ref; --start --

echo "[mcp] TR10: register from a git URL clones repo/ at the pinned ref and --start boots"
GITSRC="${TEST_ROOT}/reg10-src"
mkdir -p "${GITSRC}"
cat >"${GITSRC}/compose.yml" <<'EOF'
services:
  reg10:
    image: alpine:latest
    container_name: harness-mcp-test_reg10
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
    healthcheck:
      test: ["CMD-SHELL", "true"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 1s
networks:
  harness-net:
EOF
cat >"${GITSRC}/client-config.json" <<'EOF'
{ "mcpServers": { "reg10": { "type": "sse", "url": "http://reg10:8765/sse" } } }
EOF
(
    cd "${GITSRC}"
    git init -q -b main 2>/dev/null || { git init -q; git checkout -q -b main 2>/dev/null || true; }
    git -c user.email=t@example.invalid -c user.name=test add -A
    git -c user.email=t@example.invalid -c user.name=test commit -q -m "reg10 mcp fixture"
    git tag v0.0.1
)
harness_call mcp register reg10 --from "file://${GITSRC}" --ref v0.0.1 --start >"${TEST_ROOT}/reg10.log" 2>&1 || {
    echo "[mcp] TR10 FAIL: register --start exited non-zero" >&2
    tail -40 "${TEST_ROOT}/reg10.log" >&2
    exit 1
}
if [[ ! -d "${FAKE_INSTALL_ROOT}/state/mcp/reg10/repo/.git" ]]; then
    echo "[mcp] TR10 FAIL: source was not cloned into state/mcp/reg10/repo/" >&2
    cat "${TEST_ROOT}/reg10.log" >&2
    exit 1
fi
if ! grep -q '"repo_clone_url"' "${FAKE_INSTALL_ROOT}/state/mcp/reg10/harness-meta.json"; then
    echo "[mcp] TR10 FAIL: provenance repo_clone_url not recorded" >&2
    cat "${FAKE_INSTALL_ROOT}/state/mcp/reg10/harness-meta.json" >&2
    exit 1
fi
if ! grep -q 'v0.0.1' "${FAKE_INSTALL_ROOT}/state/mcp/reg10/harness-meta.json"; then
    echo "[mcp] TR10 FAIL: provenance repo_clone_ref (v0.0.1) not recorded" >&2
    cat "${FAKE_INSTALL_ROOT}/state/mcp/reg10/harness-meta.json" >&2
    exit 1
fi
# --start booted it: wait for the container to report healthy (60s ceiling).
deadline=$(( $(date +%s) + 60 ))
reg10_cid=""
while true; do
    reg10_cid=$(harness_docker ps -q --filter "name=^harness-mcp-test_reg10$" 2>/dev/null || true)
    if [[ -n "${reg10_cid}" ]]; then
        status=$(harness_docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${reg10_cid}" 2>/dev/null || echo none)
        if [[ "${status}" == "healthy" ]]; then break; fi
    fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] TR10 FAIL: reg10 not healthy in 60s" >&2
        harness_docker logs "${reg10_cid}" 2>&1 | tail -20 >&2 || true
        exit 1
    fi
    sleep 2
done
harness_call mcp down reg10 >/dev/null 2>&1 || true
echo "[mcp] TR10 OK"

echo "============================================================"
echo " MCP TEST PASSED"
echo "============================================================"
exit 0
