#!/usr/bin/env bash
#
# Proxy integration test.
#
# Brings up the real proxy + a mock upstream, then runs scenarios against the
# proxy's OpenAI-compatible interface (/v1/chat/completions) — the path
# opencode talks to directly, with no ollama hop:
#   A. text     — stream=false, verify choices[0].message.content + usage.
#   A2. models  — GET /v1/models forwards the upstream catalog (OpenAI list).
#   B. tool     — stream=false, verify a structured tool_calls entry with
#                 function.name + arguments (JSON string) and
#                 finish_reason=tool_calls.
#   C. forward  — verify the upstream received {"model","messages"} ONLY and
#                 the final user message carries the cooperative-prompt wrapper.
#   E. multi    — stream=false, verify TWO tool_calls are surfaced from a
#                 single response with unique call_ ids.
#   F. config   — proxy startup banner reflects the env-driven config.
#   G. stream   — stream=true, verify chat.completion.chunk SSE → data: [DONE].
#   H. tool/sse — verify a streamed delta.tool_calls entry with index,
#                 id+function.name, and arguments as a JSON *string*.
#
# Also runs proxy/test_proxy.py inside the proxy container.
#
# The proxy port is not published to the host; in-network HTTP scenarios curl
# it from inside the proxy container itself (the proxy image ships curl for its
# healthcheck), which mirrors the on-network access opencode uses.
#
# Always tears down compose state on exit. Uses a dedicated project name so
# this test doesn't collide with other compose stacks.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${REPO_ROOT}"

# shellcheck disable=SC1091
source "${REPO_ROOT}/scripts/lib/platform.sh"

PROJECT_NAME="harness-proxy-test"

echo "============================================================"
echo " harness proxy integration test"
echo "============================================================"

# --- preflight ---------------------------------------------------------------

if ! harness_docker info >/dev/null 2>&1; then
    echo "[proxy-test] ERROR: container runtime ($(harness_container_runtime)) is not reachable" >&2
    exit 1
fi

# --- temp env + override -----------------------------------------------------

ENV_FILE="$(mktemp -t harness-proxy.XXXXXX.env)"
OVERRIDE_FILE="$(mktemp -t harness-proxy.XXXXXX.yml)"

write_env() {
    local scenario="$1"
    local fixtures_dir="${2:-}"
    cat >"${ENV_FILE}" <<EOF
PROXY_API_URL=http://mockupstream:9000/v1/chat/completions
PROXY_API_KEY=test-key-1234
DEFAULT_MODEL_NAME=harness
PROXY_HOST=0.0.0.0
PROXY_PORT=8000
OUTPUT_DIR=
PROXY_TIMEOUT=30
MODEL_CONTEXT_LENGTH=200000
MOCK_SCENARIO=${scenario}
MOCK_FIXTURES_DIR=${fixtures_dir}
EOF
}

cat >"${OVERRIDE_FILE}" <<'EOF'
services:
  mockupstream:
    image: python:3.12-slim
    working_dir: /app
    environment:
      MOCK_SCENARIO: ${MOCK_SCENARIO:-text}
      MOCK_FIXTURES_DIR: ${MOCK_FIXTURES_DIR:-}
    volumes:
      - ./tests/mock_upstream.py:/app/mock_upstream.py:ro
      - ./tests/fixtures/responses:/fixtures:ro
    networks:
      - harness-net
    expose:
      - "9000"
    command: >
      sh -c "pip install --quiet --no-cache-dir flask==3.0.3 &&
             python /app/mock_upstream.py"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys;\nu=urllib.request.urlopen('http://127.0.0.1:9000/health',timeout=2);\nsys.exit(0 if u.status==200 else 1)"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 20s
EOF

write_env "text"

# Firewall allowlist for the test stack. Every harness container reads
# /etc/harness/allowlist; we generate a temp file and point compose at it
# via HARNESS_ALLOWLIST_PATH so the bind-mount in docker-compose.yml
# resolves to a real path. Superset of init-firewall.sh's verify-step
# probes (api.github.com etc.).
ALLOWLIST_FILE="$(mktemp -t harness-proxy.XXXXXX.allow)"
cat >"${ALLOWLIST_FILE}" <<'EOF'
# auto-generated by proxy_test.sh
github.com
api.github.com
codeload.github.com
raw.githubusercontent.com
objects.githubusercontent.com
pypi.org
files.pythonhosted.org
registry.npmjs.org
EOF
export HARNESS_ALLOWLIST_PATH="${ALLOWLIST_FILE}"

COMPOSE=(harness_docker compose --project-name "${PROJECT_NAME}" --env-file "${ENV_FILE}" -f docker-compose.yml -f "${OVERRIDE_FILE}")

cleanup() {
    echo "[proxy-test] cleanup: tearing down compose state"
    "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
    rm -f "${ENV_FILE}" "${OVERRIDE_FILE}" "${ALLOWLIST_FILE}"
}
trap cleanup EXIT INT TERM

# Defensive: clear any stale state from a prior run.
"${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true

# --- compose config sanity check --------------------------------------------

echo "[proxy-test] validating compose config"
"${COMPOSE[@]}" config >/dev/null

# --- bring up ----------------------------------------------------------------

echo "[proxy-test] building and starting services (mockupstream + proxy)"
"${COMPOSE[@]}" up -d --build

# --- wait for healthy --------------------------------------------------------

is_healthy() {
    local svc="$1"
    local cid
    cid="$("${COMPOSE[@]}" ps -q "${svc}" 2>/dev/null || true)"
    if [[ -z "${cid}" ]]; then return 1; fi
    local status
    status="$(harness_docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${cid}" 2>/dev/null || echo "none")"
    [[ "${status}" == "healthy" ]]
}

wait_healthy() {
    local timeout_s="$1"; shift
    local deadline=$(( $(date +%s) + timeout_s ))
    while true; do
        local all_ok=1
        for svc in "$@"; do
            if ! is_healthy "${svc}"; then all_ok=0; break; fi
        done
        if (( all_ok )); then return 0; fi
        if (( $(date +%s) >= deadline )); then return 1; fi
        sleep 2
    done
}

echo "[proxy-test] waiting up to 120s for mockupstream + proxy to be healthy"
if ! wait_healthy 120 mockupstream proxy; then
    echo "[proxy-test] ERROR: services did not become healthy" >&2
    "${COMPOSE[@]}" ps >&2 || true
    echo "--- mockupstream logs ---" >&2; "${COMPOSE[@]}" logs mockupstream >&2 || true
    echo "--- proxy logs ---"        >&2; "${COMPOSE[@]}" logs proxy        >&2 || true
    exit 1
fi
echo "[proxy-test] all services healthy"

# --- helpers -----------------------------------------------------------------

PROXY_URL="http://127.0.0.1:8000"

# Curl the proxy from inside the proxy container (the port isn't published to
# the host; the proxy image ships curl for its healthcheck).
proxy_curl() {
    "${COMPOSE[@]}" exec -T proxy curl "$@"
}

fail() {
    local label="$1"; shift
    echo "[proxy-test] FAIL: ${label}" >&2
    if [[ $# -gt 0 ]]; then echo "[proxy-test] detail: $*" >&2; fi
    echo "--- mockupstream logs ---" >&2; "${COMPOSE[@]}" logs mockupstream >&2 || true
    echo "--- proxy logs ---"        >&2; "${COMPOSE[@]}" logs proxy        >&2 || true
    exit 1
}

restart_mock_with_scenario() {
    local scenario="$1"
    write_env "${scenario}"
    echo "[proxy-test] restarting mockupstream with MOCK_SCENARIO=${scenario}"
    "${COMPOSE[@]}" up -d --force-recreate mockupstream >/dev/null
    if ! wait_healthy 60 mockupstream; then
        fail "mockupstream did not become healthy after switching to scenario '${scenario}'"
    fi
}

restart_mock_with_fixtures() {
    # Switch the mockupstream into fixture-dispatch mode. The fixtures
    # directory is already bind-mounted at /fixtures in the override; we
    # just need MOCK_FIXTURES_DIR set so the mock loads them.
    write_env "text" "/fixtures"
    echo "[proxy-test] restarting mockupstream with MOCK_FIXTURES_DIR=/fixtures"
    "${COMPOSE[@]}" up -d --force-recreate mockupstream >/dev/null
    if ! wait_healthy 60 mockupstream; then
        fail "mockupstream did not become healthy after switching to fixture mode"
    fi
}

# --- unit tests inside the proxy container ----------------------------------

echo "[proxy-test] running proxy unit tests inside the proxy container"
"${COMPOSE[@]}" run --rm proxy python -m unittest test_proxy.py -v \
    || fail "unit tests failed"

# --- Scenario A: text round-trip (stream=false) -----------------------------

echo "[proxy-test] scenario A: text round-trip (stream=false)"
restart_mock_with_scenario "text"

A_BODY="$(proxy_curl -fsS -X POST "${PROXY_URL}/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d '{"model":"harness","messages":[{"role":"user","content":"hi"}],"stream":false}')" \
    || fail "A: /v1/chat/completions request failed"
echo "[proxy-test]   A response: ${A_BODY}"
echo "${A_BODY}" | grep -q "Hello from mock upstream" \
    || fail "A: response did not contain upstream content" "${A_BODY}"
echo "${A_BODY}" | grep -qE '"object":[[:space:]]*"chat\.completion"' \
    || fail "A: response is not a chat.completion object" "${A_BODY}"
echo "${A_BODY}" | grep -qE '"finish_reason":[[:space:]]*"stop"' \
    || fail "A: finish_reason was not stop" "${A_BODY}"
# prompt_tokens is the proxy's local estimate of the translated conversation
# (what the agent actually sent), so it is present and non-zero rather than
# the upstream's reported value. completion_tokens passes through from the
# mock upstream (hardcoded 7).
echo "${A_BODY}" | grep -qE '"prompt_tokens":[[:space:]]*[1-9][0-9]*' \
    || fail "A: prompt_tokens missing or zero" "${A_BODY}"
echo "${A_BODY}" | grep -qE '"completion_tokens":[[:space:]]*7' \
    || fail "A: completion_tokens != 7 (usage not propagated)" "${A_BODY}"

# --- Scenario A2: proxy /v1/models discovery route --------------------------

echo "[proxy-test] scenario A2: proxy /v1/models forwards the upstream catalog"
# The proxy forwards GET {upstream}/v1/models; the mock returns its
# MOCK_MODELS list (default 'harness').
MODELS_JSON="$(proxy_curl -fsS "${PROXY_URL}/v1/models")" \
    || fail "A2: GET /v1/models via proxy failed"
echo "[proxy-test]   A2 /v1/models: ${MODELS_JSON}"
echo "${MODELS_JSON}" | grep -q '"harness"' \
    || fail "A2: /v1/models did not list the mock model 'harness'" "${MODELS_JSON}"
echo "${MODELS_JSON}" | grep -qE '"object":[[:space:]]*"list"' \
    || fail "A2: /v1/models response is not an OpenAI list envelope" "${MODELS_JSON}"

# --- Scenario B: tool call (stream=false) -----------------------------------

echo "[proxy-test] scenario B: tool call"
restart_mock_with_scenario "tool"

B_REQ='{
  "model": "harness",
  "messages": [{"role":"user","content":"what is the weather in Atlanta?"}],
  "tools": [{
    "type": "function",
    "function": {
      "name": "get_weather",
      "description": "Get the weather for a city.",
      "parameters": {
        "type": "object",
        "properties": {"city": {"type":"string","description":"city name"}},
        "required": ["city"]
      }
    }
  }],
  "stream": false
}'
B_BODY="$(proxy_curl -fsS -X POST "${PROXY_URL}/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d "${B_REQ}")" \
    || fail "B: /v1/chat/completions request failed"
echo "[proxy-test]   B response: ${B_BODY}"

B_CHECK="$("${COMPOSE[@]}" exec -T proxy python -c "
import json, sys
body = json.loads(sys.stdin.read())
msg = body['choices'][0]['message']
tcs = msg.get('tool_calls')
if not tcs:
    print('NO_TOOL_CALLS'); sys.exit(0)
tc = tcs[0]
if not tc.get('id', '').startswith('call_'):
    print('BAD_ID:' + str(tc.get('id'))); sys.exit(0)
fn = tc.get('function') or {}
if fn.get('name') != 'get_weather':
    print('WRONG_NAME:' + str(fn.get('name'))); sys.exit(0)
args = fn.get('arguments')
if not isinstance(args, str):
    print('ARGS_NOT_STRING:' + type(args).__name__); sys.exit(0)
if json.loads(args).get('city') != 'Atlanta':
    print('WRONG_CITY:' + args); sys.exit(0)
if body['choices'][0].get('finish_reason') != 'tool_calls':
    print('WRONG_FINISH:' + str(body['choices'][0].get('finish_reason'))); sys.exit(0)
print('OK')
" <<<"${B_BODY}")" || fail "B: failed to inspect response" "${B_BODY}"

case "${B_CHECK}" in
    OK*)              echo "[proxy-test]   B OK (structured tool_call; arguments is a JSON string)" ;;
    NO_TOOL_CALLS*)   fail "B: response had no tool_calls field" "${B_BODY}" ;;
    BAD_ID*)          fail "B: tool_call id missing or not call_-prefixed: ${B_CHECK}" "${B_BODY}" ;;
    WRONG_NAME*)      fail "B: tool_call not named get_weather: ${B_CHECK}" "${B_BODY}" ;;
    ARGS_NOT_STRING*) fail "B: tool_call arguments not a JSON string: ${B_CHECK}" "${B_BODY}" ;;
    WRONG_CITY*)      fail "B: tool_call arguments did not include city=Atlanta: ${B_CHECK}" "${B_BODY}" ;;
    WRONG_FINISH*)    fail "B: finish_reason was not tool_calls: ${B_CHECK}" "${B_BODY}" ;;
    *)                fail "B: unexpected check output: ${B_CHECK}" "${B_BODY}" ;;
esac

# --- Scenario C: forwarded request shape ------------------------------------

echo "[proxy-test] scenario C: forwarded request shape"
restart_mock_with_scenario "text"

# Send a request with tools so the cooperative prompt wrapper kicks in.
C_REQ='{
  "model": "harness",
  "messages": [{"role":"user","content":"please pick a tool"}],
  "tools": [{"type":"function","function":{"name":"get_weather","description":"weather","parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}}],
  "stream": false
}'
C_BODY="$(proxy_curl -fsS -X POST "${PROXY_URL}/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d "${C_REQ}")" \
    || fail "C: /v1/chat/completions request failed"
echo "[proxy-test]   C response (truncated): $(echo "${C_BODY}" | head -c 200)"

# Inspect the upstream's logs to confirm what the proxy forwarded.
MOCK_LOGS="$("${COMPOSE[@]}" logs --tail=200 mockupstream 2>&1 || true)"
LAST_BODY_LINE="$(echo "${MOCK_LOGS}" | grep -E '\[mock-upstream\] (POST|PUT) ' | tail -1)"
if [[ -z "${LAST_BODY_LINE}" ]]; then
    fail "C: no recent POST seen in mockupstream logs" "${MOCK_LOGS}"
fi
# Extract the body=<json> portion. The body= prefix is followed by the JSON.
FORWARDED_BODY="${LAST_BODY_LINE#*body=}"
echo "[proxy-test]   forwarded body: ${FORWARDED_BODY}"

# Verify only the two allowed top-level keys are present. We check via python
# inside the proxy container so we don't need jq on the host.
KEY_CHECK="$("${COMPOSE[@]}" exec -T proxy python -c "
import json, sys
body = json.loads(sys.stdin.read())
keys = sorted(body.keys())
if keys != ['messages', 'model']:
    print('UNEXPECTED_KEYS:' + ','.join(keys))
    sys.exit(0)
# Default mode is now 'hybrid': the last user message carries the live probe
# wrapped in <<<BEGIN_USER_REQUEST>>> markers (placed FIRST) followed by the
# recency reminder with its per-tool legend, while the full tool scaffolding
# (### Tool Usage Instructions + the AGENT_TOOLS block) lives at the HEAD of
# the conversation, not on the last user message.
msgs = body['messages']
last = msgs[-1]
last_content = last.get('content','')
if last.get('role') != 'user':
    print('LAST_NOT_USER:' + str(last.get('role')))
    sys.exit(0)
if 'Reminder' not in last_content:
    print('NO_REMINDER_PREFIX')
    sys.exit(0)
if 'do not invent' not in last_content:
    print('REMINDER_MISSING_DO_NOT_INVENT')
    sys.exit(0)
if 'Tools — one entry per tool' not in last_content:
    print('REMINDER_MISSING_TOOLS_LEGEND')
    sys.exit(0)
# The reminder points the model back at the AGENT_TOOLS block by name.
if '<<<BEGIN_AGENT_TOOLS>>>' not in last_content:
    print('REMINDER_MISSING_AGENT_TOOLS_POINTER')
    sys.exit(0)
# The probe (live user request) is wrapped in USER_REQUEST markers and placed
# FIRST under hybrid; the reminder sits AFTER the wrap.
if '<<<BEGIN_USER_REQUEST>>>' not in last_content:
    print('NO_USER_REQUEST_WRAP')
    sys.exit(0)
if last_content.index('Reminder') <= last_content.index('<<<END_USER_REQUEST>>>'):
    print('REMINDER_NOT_AFTER_USER_REQUEST')
    sys.exit(0)
# The full tool list / instructions header must NOT be on the last user
# message — those live in the head under hybrid.
if '### Tool Usage Instructions' in last_content:
    print('FULL_INSTRUCTIONS_ON_LAST_USER')
    sys.exit(0)
if '<<<END_AGENT_TOOLS>>>' in last_content:
    print('FULL_TOOL_LIST_ON_LAST_USER')
    sys.exit(0)
# Verify the scaffolding lives at the head of the conversation.
head = '\n'.join(m.get('content','') for m in msgs[:-1])
if '### Tool Usage Instructions' not in head:
    print('NO_INSTRUCTIONS_HEADER_IN_HEAD')
    sys.exit(0)
if '<<<BEGIN_AGENT_TOOLS>>>' not in head:
    print('NO_AGENT_TOOLS_IN_HEAD')
    sys.exit(0)
# Passthrough: the forwarded model is the inbound request's model ('harness'),
# not a fixed PROXY_API_MODEL.
if body['model'] != 'harness':
    print('WRONG_MODEL:' + str(body['model']))
    sys.exit(0)
print('OK')
" <<<"${FORWARDED_BODY}")" || fail "C: failed to inspect forwarded body" "${FORWARDED_BODY}"

case "${KEY_CHECK}" in
    *OK*) ;;
    *WRONG_MODEL*)                 fail "C: forwarded model is not the passed-through request model: ${KEY_CHECK}" "${FORWARDED_BODY}" ;;
    *UNEXPECTED_KEYS*)              fail "C: forwarded body had keys other than {model,messages}: ${KEY_CHECK}" "${FORWARDED_BODY}" ;;
    *LAST_NOT_USER*)               fail "C: last forwarded message is not a user message: ${KEY_CHECK}" "${FORWARDED_BODY}" ;;
    *NO_REMINDER_PREFIX*)          fail "C: hybrid last user message is missing the [Reminder …] prefix" "${FORWARDED_BODY}" ;;
    *REMINDER_MISSING_DO_NOT_INVENT*) fail "C: hybrid reminder is missing the 'do not invent' rule" "${FORWARDED_BODY}" ;;
    *REMINDER_MISSING_TOOLS_LEGEND*) fail "C: hybrid reminder is missing the 'Tools — one entry per tool' legend" "${FORWARDED_BODY}" ;;
    *REMINDER_MISSING_AGENT_TOOLS_POINTER*) fail "C: hybrid reminder does not point back at <<<BEGIN_AGENT_TOOLS>>>" "${FORWARDED_BODY}" ;;
    *NO_USER_REQUEST_WRAP*)        fail "C: hybrid probe is not wrapped in <<<BEGIN_USER_REQUEST>>> markers" "${FORWARDED_BODY}" ;;
    *REMINDER_NOT_AFTER_USER_REQUEST*) fail "C: hybrid reminder should sit AFTER the USER_REQUEST wrap (live ask comes first)" "${FORWARDED_BODY}" ;;
    *FULL_INSTRUCTIONS_ON_LAST_USER*) fail "C: full tool instructions leaked onto the last user message (should be in head)" "${FORWARDED_BODY}" ;;
    *FULL_TOOL_LIST_ON_LAST_USER*) fail "C: full tool list leaked onto the last user message (should be in head)" "${FORWARDED_BODY}" ;;
    *NO_INSTRUCTIONS_HEADER_IN_HEAD*) fail "C: tool instructions header is missing from the conversation head" "${FORWARDED_BODY}" ;;
    *NO_AGENT_TOOLS_IN_HEAD*)      fail "C: <<<BEGIN_AGENT_TOOLS>>> block is missing from the conversation head" "${FORWARDED_BODY}" ;;
    *)                              fail "C: unexpected key-check output: ${KEY_CHECK}" "${FORWARDED_BODY}" ;;
esac

# --- Scenario E: multiple tool calls in one response ------------------------
#
# Exercises the proxy's multi-call extraction end-to-end via
# tests/fixtures/responses/07_multi_tool_calls.json. The fixture's
# response has TWO ```json``` blocks; the proxy must surface BOTH as
# distinct tool_calls with unique call_ ids.

echo "[proxy-test] scenario E: multiple tool calls in one response"
restart_mock_with_fixtures

E_REQ='{
  "model": "harness",
  "messages": [{"role":"user","content":"please read both files"}],
  "stream": false,
  "tools": [{
    "type": "function",
    "function": {
      "name": "Read",
      "description": "Read a file",
      "parameters": {
        "type": "object",
        "properties": {"file_path": {"type":"string"}},
        "required": ["file_path"]
      }
    }
  }]
}'
E_BODY="$(proxy_curl -fsS -X POST "${PROXY_URL}/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d "${E_REQ}")" \
    || fail "E: /v1/chat/completions request failed"
echo "[proxy-test]   E response (truncated): $(echo "${E_BODY}" | head -c 400)"

E_TC_CHECK="$("${COMPOSE[@]}" exec -T proxy python -c "
import json, sys
body = json.loads(sys.stdin.read())
tool_calls = body['choices'][0]['message'].get('tool_calls')
if not tool_calls:
    print('NO_TOOL_CALLS')
    sys.exit(0)
if len(tool_calls) != 2:
    print(f'WRONG_COUNT:{len(tool_calls)}')
    sys.exit(0)
p1 = json.loads(tool_calls[0]['function']['arguments']).get('file_path')
p2 = json.loads(tool_calls[1]['function']['arguments']).get('file_path')
if p1 == p2:
    print(f'SAME_PATH:{p1}')
    sys.exit(0)
id1 = tool_calls[0].get('id', '')
id2 = tool_calls[1].get('id', '')
if id1 == id2 or not id1.startswith('call_') or not id2.startswith('call_'):
    print(f'BAD_IDS:{id1}/{id2}')
    sys.exit(0)
n1 = tool_calls[0]['function'].get('name', '')
n2 = tool_calls[1]['function'].get('name', '')
if n1 != 'Read' or n2 != 'Read':
    print(f'WRONG_NAMES:{n1}/{n2}')
    sys.exit(0)
print(f'OK paths={p1},{p2} ids={id1},{id2}')
" <<<"${E_BODY}")" || fail "E: failed to inspect response" "${E_BODY}"

case "${E_TC_CHECK}" in
    OK*)                  echo "[proxy-test]   E ${E_TC_CHECK}" ;;
    NO_TOOL_CALLS*)       fail "E: response carried no tool_calls field" "${E_BODY}" ;;
    WRONG_COUNT*)         fail "E: expected 2 tool_calls, got ${E_TC_CHECK#WRONG_COUNT:}" "${E_BODY}" ;;
    SAME_PATH*)           fail "E: both tool_calls had same file_path: ${E_TC_CHECK#SAME_PATH:}" "${E_BODY}" ;;
    BAD_IDS*)             fail "E: tool_call ids missing or duplicate: ${E_TC_CHECK#BAD_IDS:}" "${E_BODY}" ;;
    WRONG_NAMES*)         fail "E: expected both tool_calls named 'Read': ${E_TC_CHECK#WRONG_NAMES:}" "${E_BODY}" ;;
    *)                    fail "E: unexpected check output: ${E_TC_CHECK}" "${E_BODY}" ;;
esac
echo "[proxy-test]   E OK (2 distinct Read calls, unique call_ ids)"

# --- Scenario F: env-driven startup config ----------------------------------
#
# Several env vars set in write_env() must be honored by the proxy. The
# proxy prints a startup banner that echoes the values it actually
# consumed (listening on, upstream key redacted, debug-dumps status). We
# scrape the proxy container logs to assert each variable surfaced.

echo "[proxy-test] scenario F: env-driven startup config"

PROXY_LOGS="$("${COMPOSE[@]}" logs proxy 2>&1 || true)"
if [[ -z "${PROXY_LOGS}" ]]; then
    fail "F: could not capture proxy logs"
fi

# Inventory P003: Proxy reads PROXY_HOST from env (test sets 0.0.0.0).
# Startup banner echoes "listening on: <host>:<port>" with the actual
# value the Flask app bound to.
echo "${PROXY_LOGS}" | grep -qE 'listening on:[[:space:]]+0\.0\.0\.0:8000' \
    || fail "F/P003: proxy banner did not echo PROXY_HOST=0.0.0.0" "${PROXY_LOGS}"

# Inventory P004: Proxy reads PROXY_PORT from env (test sets 8000).
# Same banner line; the ":8000" suffix confirms the port env was consumed.
echo "${PROXY_LOGS}" | grep -qE 'listening on:[[:space:]]+0\.0\.0\.0:8000' \
    || fail "F/P004: proxy banner did not echo PROXY_PORT=8000" "${PROXY_LOGS}"

# Inventory P008: Proxy reads PROXY_TIMEOUT from env (test sets 30).
# Banner emits "   timeout:        <N>s\n".
echo "${PROXY_LOGS}" | grep -qE 'timeout:[[:space:]]+30s' \
    || fail "F/P008: proxy banner did not echo PROXY_TIMEOUT=30s" "${PROXY_LOGS}"

# Inventory P006: Proxy reads PROXY_API_KEY from env (test sets test-key-1234).
# _redact_key shows first-4 + "..." + last-4 for keys >8 chars, so
# "test-key-1234" (13 chars) becomes "test...1234".
echo "${PROXY_LOGS}" | grep -qE 'upstream key:[[:space:]]+test\.\.\.1234' \
    || fail "F/P006: proxy banner did not echo redacted PROXY_API_KEY" "${PROXY_LOGS}"
# Also assert the raw key is NOT printed (regression guard: the redactor
# must hide the middle of the key).
if echo "${PROXY_LOGS}" | grep -qE 'upstream key:[[:space:]]+test-key-1234'; then
    fail "F/P006: proxy banner leaked raw PROXY_API_KEY" "${PROXY_LOGS}"
fi

# Inventory P012: Proxy reads OUTPUT_DIR from env (test sets empty).
# Inventory P050: Debug dumps are skipped silently when OUTPUT_DIR is unset.
# When OUTPUT_DIR is empty, the banner reports
# "debug dumps:    disabled (OUTPUT_DIR not set)" and no save_debug_file
# errors are logged. Asserting BOTH the banner line and the absence of
# "failed to save debug file" lines covers the silent-skip path.
echo "${PROXY_LOGS}" | grep -qE 'debug dumps:[[:space:]]+disabled \(OUTPUT_DIR not set\)' \
    || fail "F/P012: proxy banner did not echo OUTPUT_DIR-disabled status" "${PROXY_LOGS}"
if echo "${PROXY_LOGS}" | grep -q 'failed to save debug file'; then
    fail "F/P050: proxy logged save_debug_file errors despite OUTPUT_DIR being unset" "${PROXY_LOGS}"
fi
# Stronger silent-skip guard: when OUTPUT_DIR is empty the init_output_dir
# warning ("not writable") must NOT appear — that message is only emitted
# for a SET-but-unwritable value, not an empty one.
if echo "${PROXY_LOGS}" | grep -qE "OUTPUT_DIR '' is not writable"; then
    fail "F/P050: proxy treated empty OUTPUT_DIR as a writable-check failure" "${PROXY_LOGS}"
fi

echo "[proxy-test]   F OK (env-driven startup banner reflects configured values)"

# --- Scenario G: OpenAI-compatible inbound (/v1/chat/completions, SSE) -------
#
# opencode talks to the proxy directly over the OpenAI Chat Completions
# interface (via @ai-sdk/openai-compatible). The AI SDK always sets
# stream:true and parses text/event-stream. Verify the proxy accepts an
# OpenAI request and streams chat.completion.chunk objects ending in
# `data: [DONE]`.

echo "[proxy-test] scenario G: OpenAI /v1/chat/completions SSE"
restart_mock_with_scenario "text"

G_RAW="$(proxy_curl -fsS -N -X POST "${PROXY_URL}/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d '{"model":"harness","messages":[{"role":"user","content":"hi"}],"stream":true}')" \
    || fail "G: POST /v1/chat/completions (stream=true) failed"
echo "[proxy-test]   G raw (first 300 chars): $(echo "${G_RAW}" | head -c 300)"

echo "${G_RAW}" | grep -q '^data: ' \
    || fail "G: response had no SSE 'data:' lines" "${G_RAW}"
echo "${G_RAW}" | grep -q '^data: \[DONE\]' \
    || fail "G: SSE stream did not terminate with [DONE]" "${G_RAW}"
echo "${G_RAW}" | grep -qE '"object":[[:space:]]*"chat\.completion\.chunk"' \
    || fail "G: no chat.completion.chunk object in stream" "${G_RAW}"
echo "${G_RAW}" | grep -q 'Hello from mock upstream' \
    || fail "G: streamed content missing upstream text" "${G_RAW}"
echo "${G_RAW}" | grep -qE '"finish_reason":[[:space:]]*"stop"' \
    || fail "G: stream missing finish_reason=stop" "${G_RAW}"
echo "[proxy-test]   G OK (OpenAI SSE: chat.completion.chunk stream → [DONE])"

# --- Scenario H: OpenAI tool call over SSE ----------------------------------
#
# The AI SDK requires each streamed tool-call delta to carry `index` (always),
# `id`+`function.name` on the first fragment, and `function.arguments` as a
# JSON *string* that accumulates to valid JSON. Verify the proxy emits exactly
# that shape end-to-end through the cooperative-prompt mediation.

echo "[proxy-test] scenario H: OpenAI tool call over SSE"
restart_mock_with_scenario "tool"

H_REQ='{
  "model": "harness",
  "messages": [{"role":"user","content":"what is the weather in Atlanta?"}],
  "stream": true,
  "tools": [{
    "type": "function",
    "function": {
      "name": "get_weather",
      "description": "Get the weather for a city.",
      "parameters": {"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}
    }
  }]
}'
H_RAW="$(proxy_curl -fsS -N -X POST "${PROXY_URL}/v1/chat/completions" \
    -H 'Content-Type: application/json' \
    -d "${H_REQ}")" \
    || fail "H: POST /v1/chat/completions (tool) failed"
echo "[proxy-test]   H raw (first 400 chars): $(echo "${H_RAW}" | head -c 400)"

H_CHECK="$("${COMPOSE[@]}" exec -T proxy python -c "
import json, sys
tool_calls = None
finish = None
for line in sys.stdin.read().splitlines():
    line = line.strip()
    if not line.startswith('data:'):
        continue
    payload = line[len('data:'):].strip()
    if payload == '[DONE]':
        continue
    try:
        chunk = json.loads(payload)
    except ValueError:
        continue
    if chunk.get('object') != 'chat.completion.chunk':
        print('WRONG_OBJECT:' + str(chunk.get('object')))
        sys.exit(0)
    for ch in chunk.get('choices') or []:
        d = ch.get('delta') or {}
        if d.get('tool_calls'):
            tool_calls = d['tool_calls']
        if ch.get('finish_reason'):
            finish = ch['finish_reason']
if tool_calls is None:
    print('NO_TOOL_CALLS'); sys.exit(0)
tc = tool_calls[0]
if tc.get('index') != 0:
    print('NO_INDEX:' + str(tc.get('index'))); sys.exit(0)
if not tc.get('id'):
    print('NO_ID'); sys.exit(0)
fn = tc.get('function') or {}
if fn.get('name') != 'get_weather':
    print('WRONG_NAME:' + str(fn.get('name'))); sys.exit(0)
args = fn.get('arguments')
if not isinstance(args, str):
    print('ARGS_NOT_STRING:' + str(type(args).__name__)); sys.exit(0)
if json.loads(args).get('city') != 'Atlanta':
    print('WRONG_CITY:' + args); sys.exit(0)
if finish != 'tool_calls':
    print('WRONG_FINISH:' + str(finish)); sys.exit(0)
print('OK')
" <<<"${H_RAW}")" || fail "H: failed to inspect SSE tool stream" "${H_RAW}"

case "${H_CHECK}" in
    OK*)             echo "[proxy-test]   H OK (OpenAI tool_call over SSE; arguments is a JSON string)" ;;
    NO_TOOL_CALLS*)  fail "H: no SSE delta carried tool_calls" "${H_RAW}" ;;
    ARGS_NOT_STRING*) fail "H: tool_call arguments not a JSON string (AI SDK requires string): ${H_CHECK}" "${H_RAW}" ;;
    *)               fail "H: OpenAI tool-call SSE check failed: ${H_CHECK}" "${H_RAW}" ;;
esac

echo "============================================================"
echo " PROXY TEST PASSED"
echo "============================================================"
exit 0
