#!/usr/bin/env bash
#
# scripts/mcp_test.sh — exercise the `harness mcp` lifecycle without
# pulling Serena. We synthesize a tiny fake MCP entry under a tmpdir,
# point HARNESS_REGISTRY_DIR at it, and walk through enable / start /
# verify-network / disable / verify-removed.
#
# The fake MCP is `python:3.12-slim` running `python -m http.server`. It
# exposes nothing of substance; we use it purely to validate that:
#   - registry discovery finds it,
#   - enable copies it into the active tree,
#   - harness start brings it up on the harness-net network,
#   - the merged client config lands in the agent home,
#   - disable cleanly removes the active entry but preserves data/.
#
# Project name is fixed to harness-mcp-test so this never collides with a
# real harness instance running on the same daemon.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Cross-platform helpers (harness_docker, harness_docker_path).
# shellcheck source=lib/platform.sh
source "${REPO_ROOT}/scripts/lib/platform.sh"

PROJECT_NAME="harness-mcp-test"

echo "============================================================"
echo " harness MCP lifecycle test"
echo "============================================================"

# --- preflight --------------------------------------------------------------

if ! docker info >/dev/null 2>&1; then
    echo "[mcp] ERROR: docker daemon not reachable" >&2
    exit 1
fi

# --- staging ----------------------------------------------------------------
#
# We build a self-contained "fake install root" mirroring the real layout
# the harness script expects. The registry override lets us inject our
# fake MCP without touching the real mcp-registry/ in the repo (which the
# user might want to ship to other people).

TEST_ROOT="$(mktemp -d -t harness-mcp-test.XXXXXX)"
FAKE_REGISTRY="${TEST_ROOT}/fake-registry"
FAKE_INSTALL_ROOT="${TEST_ROOT}/install-root"

mkdir -p "${FAKE_INSTALL_ROOT}" \
         "${FAKE_REGISTRY}/_test_mcp"

# Symlink the repo as <fake-install-root>/harness so the script's
# realpath/dirname walk lands in a sensible place. HARNESS_INSTALL_ROOT
# pins it explicitly anyway, but the symlink lets `harness` exist on the
# expected path.
ln -s "${REPO_ROOT}" "${FAKE_INSTALL_ROOT}/harness"

cleanup() {
    local rc=$?
    echo "[mcp] cleanup (rc=${rc})"

    if [[ -x "${FAKE_INSTALL_ROOT}/harness/harness" ]]; then
        HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
        HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
        HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}" \
            "${FAKE_INSTALL_ROOT}/harness/harness" down >/dev/null 2>&1 || true
    fi
    docker compose --project-name "${PROJECT_NAME}" \
        -f "${REPO_ROOT}/docker-compose.yml" \
        down -v --remove-orphans >/dev/null 2>&1 || true

    if [[ -d "${TEST_ROOT}" ]]; then
        if ! rm -rf "${TEST_ROOT}" 2>/dev/null; then
            harness_docker run --rm -v "$(harness_docker_path "${TEST_ROOT}"):/target" --user 0:0 alpine \
                sh -c 'rm -rf /target/* /target/.[!.]* 2>/dev/null || true' \
                >/dev/null 2>&1 || true
            rm -rf "${TEST_ROOT}" 2>/dev/null || true
        fi
    fi
    exit "${rc}"
}
trap cleanup EXIT INT TERM

cat >"${FAKE_INSTALL_ROOT}/.env" <<'EOF'
PROXY_API_URL=http://placeholder.invalid/v1/chat/completions
PROXY_API_KEY=test-key-1234
PROXY_API_MODEL=test-model
PROXY_HOST=0.0.0.0
PROXY_PORT=8000
OUTPUT_DIR=
PROXY_TIMEOUT=30
OLLAMA_VERSION=0.21.2
OLLAMA_AGENT_MODEL=harness
OLLAMA_CONTEXT_LENGTH=200000
PUBLISH_OLLAMA_PORT=
EOF

# Firewall allowlist. The .env above points PROXY_API_URL at
# placeholder.invalid, which the proxy entrypoint guardrail validates
# against this list, so include it explicitly.
ALLOWLIST_FILE="${FAKE_INSTALL_ROOT}/.harness-allowlist"
cat >"${ALLOWLIST_FILE}" <<'EOF'
# auto-generated by mcp_test.sh
github.com
api.github.com
codeload.github.com
raw.githubusercontent.com
objects.githubusercontent.com
pypi.org
files.pythonhosted.org
registry.npmjs.org
placeholder.invalid
EOF
# Convert host path for Docker Desktop's WSL2 backend (Windows). On Linux
# this is a passthrough; on Windows /tmp/... and /c/... are rewritten to
# C:/... so the bind mount actually exposes the file inside the container.
export HARNESS_ALLOWLIST_PATH="$(harness_docker_path "${ALLOWLIST_FILE}")"

# --- fake MCP fixture -------------------------------------------------------
#
# compose.yml: lightweight HTTP service. Network is declared with the
# matching short name as the main compose file (no external/no name) so
# compose merges them into a single project-namespaced network. This is
# the same shape the production Serena fixture uses.

cat >"${FAKE_REGISTRY}/_test_mcp/compose.yml" <<'EOF'
services:
  test_mcp:
    image: python:3.12-slim
    container_name: harness-mcp-test_test_mcp
    networks:
      - harness-net
    profiles:
      - mcp
    command: python -m http.server 8765 --bind 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://127.0.0.1:8765/\",timeout=2).status==200 else 1)'"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 5s
networks:
  harness-net:
EOF

cat >"${FAKE_REGISTRY}/_test_mcp/client-config.json" <<'EOF'
{
  "mcpServers": {
    "test_mcp": {
      "type": "sse",
      "url": "http://test_mcp:8765/sse"
    }
  }
}
EOF

cat >"${FAKE_REGISTRY}/_test_mcp/README.md" <<'EOF'
# _test_mcp — fixture used by scripts/mcp_test.sh.
EOF

# Sanity: also register a "non-test" entry so we can verify list filtering.
mkdir -p "${FAKE_REGISTRY}/dummy"
cat >"${FAKE_REGISTRY}/dummy/compose.yml" <<'EOF'
services:
  dummy:
    image: alpine:latest
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
cat >"${FAKE_REGISTRY}/dummy/client-config.json" <<'EOF'
{ "mcpServers": { "dummy": { "type": "sse", "url": "http://dummy:1/" } } }
EOF

# --- helper -----------------------------------------------------------------

harness_call() {
    HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
    HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
    HARNESS_REGISTRY_DIR="${FAKE_REGISTRY}" \
        "${FAKE_INSTALL_ROOT}/harness/harness" "$@"
}

# Defensive: clear any stragglers from a prior run.
docker compose --project-name "${PROJECT_NAME}" \
    -f "${REPO_ROOT}/docker-compose.yml" \
    down -v --remove-orphans >/dev/null 2>&1 || true

# --- T1: list shows registry entries, none installed -----------------------

echo "[mcp] T1: harness mcp list — registry only, none installed"
list_out=$(harness_call mcp list)
echo "${list_out}" | sed 's/^/  | /'
# `_test_mcp` should be hidden (underscore-prefixed test fixtures don't
# show in user-facing list). `dummy` should appear with state=available.
if ! grep -Eq 'dummy[[:space:]]+available' <<<"${list_out}"; then
    echo "[mcp] T1 FAIL: dummy should be listed with state=available" >&2
    exit 1
fi
if grep -q '_test_mcp' <<<"${list_out}"; then
    echo "[mcp] T1 FAIL: _test_mcp should be hidden from list (underscore-prefixed)" >&2
    exit 1
fi
echo "[mcp] T1 OK"

# --- T2: install unknown errors with the available list -------------------

echo "[mcp] T2: harness mcp install nope (unknown name)"
set +e
err_out=$(harness_call mcp install nope 2>&1)
err_rc=$?
set -e
if (( err_rc == 0 )); then
    echo "[mcp] T2 FAIL: install nope unexpectedly succeeded" >&2
    exit 1
fi
if ! grep -qi 'unknown MCP' <<<"${err_out}"; then
    echo "[mcp] T2 FAIL: error doesn't mention 'unknown MCP': ${err_out}" >&2
    exit 1
fi
echo "[mcp] T2 OK"

# --- T3: install copies entry into active tree + writes harness-meta.json -

echo "[mcp] T3: harness mcp install _test_mcp"
harness_call mcp install _test_mcp >"${TEST_ROOT}/install.log" 2>&1
echo "  | $(grep -E '^(installed|state)' "${TEST_ROOT}/install.log" || true)"

if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T3 FAIL: compose.yml not copied" >&2
    cat "${TEST_ROOT}/install.log" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/client-config.json" ]]; then
    echo "[mcp] T3 FAIL: client-config.json not copied" >&2
    exit 1
fi
if [[ ! -d "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/data" ]]; then
    echo "[mcp] T3 FAIL: data/ not pre-created" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json" ]]; then
    echo "[mcp] T3 FAIL: harness-meta.json not written on install" >&2
    exit 1
fi
echo "[mcp] T3 OK"

# --- T4: re-install without --force fails ----------------------------------

echo "[mcp] T4: re-install without --force fails"
set +e
re_out=$(harness_call mcp install _test_mcp 2>&1)
re_rc=$?
set -e
if (( re_rc == 0 )); then
    echo "[mcp] T4 FAIL: re-install succeeded without --force" >&2
    echo "${re_out}" >&2
    exit 1
fi
echo "[mcp] T4 OK (rc=${re_rc})"

# --- T5: harness start brings up the fake MCP -------------------------------

echo "[mcp] T5: harness start with active MCP"
harness_call start >"${TEST_ROOT}/start.log" 2>&1 || {
    echo "[mcp] T5 FAIL: start exited non-zero" >&2
    tail -50 "${TEST_ROOT}/start.log" >&2
    exit 1
}

# Wait for the fake MCP container to become healthy (its compose file has
# a healthcheck; 60s ceiling).
deadline=$(( $(date +%s) + 60 ))
mcp_cid=""
while true; do
    mcp_cid=$(docker compose --project-name "${PROJECT_NAME}" \
        -f "${REPO_ROOT}/docker-compose.yml" \
        -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" \
        ps -q test_mcp 2>/dev/null || true)
    if [[ -n "${mcp_cid}" ]]; then
        status=$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${mcp_cid}" 2>/dev/null || echo "none")
        if [[ "${status}" == "healthy" ]]; then
            break
        fi
    fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T5 FAIL: test_mcp not healthy in 60s" >&2
        docker compose --project-name "${PROJECT_NAME}" \
            -f "${REPO_ROOT}/docker-compose.yml" \
            -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ps >&2 || true
        docker logs "${mcp_cid}" 2>&1 | tail -30 >&2 || true
        exit 1
    fi
    sleep 2
done
echo "[mcp] T5 OK"

# --- T6: list now shows _test_mcp as enabled + running ---------------------
#
# (Listing matches by underscore-prefix; from T1 we know it's hidden in
# user-facing output. So we instead verify via `mcp list` that the active
# entry is reflected in the running state — the fact that T5 succeeded
# already proves the active tree was discovered.)

# Verify any-mcp-active branch ran by checking that the start log invoked
# --profile mcp. We emit it via compose's verbose output indirectly — the
# easiest signal is that the test_mcp container is up.
echo "[mcp] T6: services up after start"
ollama_cid=$(docker compose --project-name "${PROJECT_NAME}" \
    -f "${REPO_ROOT}/docker-compose.yml" \
    -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" \
    ps -q ollama 2>/dev/null || true)
if [[ -z "${ollama_cid}" ]]; then
    echo "[mcp] T6 FAIL: ollama container not present (unrelated regression?)" >&2
    exit 1
fi
echo "[mcp] T6 OK"

# --- T7: agent client config gets the merged entry -------------------------
#
# We don't launch a real agent here (image may not be built). Instead we
# call the same code path harness uses internally: mkdir agent dir,
# trigger the merge by running `harness claude` against an unbuilt image
# — the script writes the side file BEFORE checking image existence.
# Actually: the script writes the side file AFTER the image-existence
# check passes... let me re-examine. (See the harness script: order is
# image check, then write_agent_mcp_config in run_agent.)
#
# Easier: invoke a no-op subcommand that hits ensure_dirs +
# write_agent_mcp_config. There isn't one, so we synthesize the work by
# stashing a real agent image first. Skip this if no image is present —
# the integration check happens in full_pipeline_test.sh.
#
# Simpler approach: directly test the side-effect on the host. Once
# enabled, we run a harness invocation that triggers the merge. Use
# `harness claude -p` against an unbuilt image: the script enters
# run_agent, calls write_agent_mcp_config, then errors on the image.

echo "[mcp] T7: merged client config side file"
mkdir -p "${FAKE_INSTALL_ROOT}/state/agent/home"
# Stash any real claude image so we can deterministically hit the
# image-not-found path.
stash_tag=""
if docker image inspect harness-agent:latest >/dev/null 2>&1; then
    stash_tag="harness-agent:mcp-test-stash-$$"
    docker tag harness-agent:latest "${stash_tag}" >/dev/null
    docker rmi harness-agent:latest >/dev/null 2>&1 || true
fi
restore_image() {
    if [[ -n "${stash_tag}" ]]; then
        docker tag "${stash_tag}" harness-agent:latest >/dev/null 2>&1 || true
        docker rmi "${stash_tag}" >/dev/null 2>&1 || true
        stash_tag=""
    fi
}
trap 'restore_image; cleanup' EXIT INT TERM

set +e
harness_call claude -p "ignored" >/dev/null 2>&1
set -e
restore_image
trap cleanup EXIT INT TERM

side_file="${FAKE_INSTALL_ROOT}/state/agent/home/.harness-mcp-servers.json"
if [[ ! -f "${side_file}" ]]; then
    echo "[mcp] T7 FAIL: ${side_file} not written" >&2
    exit 1
fi
if ! grep -q 'test_mcp' "${side_file}"; then
    echo "[mcp] T7 FAIL: side file does not mention test_mcp" >&2
    cat "${side_file}" >&2
    exit 1
fi
if ! grep -q '"http://test_mcp:8765/sse"' "${side_file}"; then
    echo "[mcp] T7 FAIL: side file missing the test_mcp url" >&2
    cat "${side_file}" >&2
    exit 1
fi
echo "[mcp] T7 OK"

# --- T8: mcp status reports installed-enabled ------------------------------

echo "[mcp] T8: harness mcp status _test_mcp"
status_out=$(harness_call mcp status _test_mcp)
echo "${status_out}" | sed 's/^/  | /'
if ! grep -Eq '^state:[[:space:]]+installed-enabled' <<<"${status_out}"; then
    echo "[mcp] T8 FAIL: status missing 'state: installed-enabled'" >&2
    exit 1
fi
if ! grep -Eq '^enabled:[[:space:]]+true' <<<"${status_out}"; then
    echo "[mcp] T8 FAIL: status missing 'enabled: true'" >&2
    exit 1
fi
if ! grep -Eq '^services:[[:space:]]+test_mcp' <<<"${status_out}"; then
    echo "[mcp] T8 FAIL: status missing services list" >&2
    exit 1
fi
echo "[mcp] T8 OK"

# --- T9: state-flag disable (no --force) keeps files, flips enabled --------

echo "[mcp] T9: harness mcp disable _test_mcp (state toggle, no --force)"
disable_out=$(harness_call mcp disable _test_mcp 2>&1)
echo "${disable_out}" | sed 's/^/  | /'
if ! grep -q "^disabled: _test_mcp" <<<"${disable_out}"; then
    echo "[mcp] T9 FAIL: expected 'disabled: _test_mcp' message" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T9 FAIL: compose.yml unexpectedly removed by state-flag disable" >&2
    exit 1
fi
if ! grep -q '"enabled": false' "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json"; then
    echo "[mcp] T9 FAIL: harness-meta.json should report enabled=false" >&2
    cat "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json" >&2
    exit 1
fi
# status should now say installed-disabled.
# Capture first then grep — under `set -euo pipefail`, piping a multi-line
# producer into `grep -q` causes SIGPIPE on the producer (rc=141), which
# pipefail elevates to the pipeline rc, and `if !` flips that to truthy.
status_t9_out=$(harness_call mcp status _test_mcp)
if ! grep -Eq '^state:[[:space:]]+installed-disabled' <<<"${status_t9_out}"; then
    echo "[mcp] T9 FAIL: status should report installed-disabled" >&2
    echo "${status_t9_out}" >&2
    exit 1
fi
echo "[mcp] T9 OK"

# --- T10: post-disable start drops the MCP service -------------------------

echo "[mcp] T10: post-disable start drops the MCP service"
harness_call start >"${TEST_ROOT}/start2.log" 2>&1 || {
    echo "[mcp] T10 FAIL: start exited non-zero after state-flag disable" >&2
    tail -30 "${TEST_ROOT}/start2.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 30 ))
while true; do
    cid=$(docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -z "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T10 FAIL: test_mcp container still running after state-flag disable" >&2
        exit 1
    fi
    sleep 2
done
echo "[mcp] T10 OK"

# --- T11: mcp up brings a disabled MCP back up manually --------------------

echo "[mcp] T11: harness mcp up _test_mcp (manual control of disabled MCP)"
harness_call mcp up _test_mcp >"${TEST_ROOT}/up.log" 2>&1 || {
    echo "[mcp] T11 FAIL: mcp up exited non-zero" >&2
    tail -30 "${TEST_ROOT}/up.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 60 ))
while true; do
    cid=$(docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -n "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T11 FAIL: mcp up did not start the container" >&2
        cat "${TEST_ROOT}/up.log" >&2
        exit 1
    fi
    sleep 2
done
# Even though container is up, enabled flag should still be false (mcp up
# does not flip it).
if ! grep -q '"enabled": false' "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json"; then
    echo "[mcp] T11 FAIL: 'mcp up' must not flip enabled flag" >&2
    exit 1
fi
echo "[mcp] T11 OK"

# --- T12: mcp down stops the container without changing enabled flag -------

echo "[mcp] T12: harness mcp down _test_mcp"
harness_call mcp down _test_mcp >"${TEST_ROOT}/down.log" 2>&1 || {
    echo "[mcp] T12 FAIL: mcp down exited non-zero" >&2
    tail -30 "${TEST_ROOT}/down.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 30 ))
while true; do
    cid=$(docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -z "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T12 FAIL: mcp down did not stop the container" >&2
        exit 1
    fi
    sleep 2
done
echo "[mcp] T12 OK"

# --- T13: mcp enable (state toggle) restores auto-start --------------------

echo "[mcp] T13: harness mcp enable _test_mcp (state toggle restore)"
enable_out=$(harness_call mcp enable _test_mcp 2>&1)
echo "${enable_out}" | sed 's/^/  | /'
if ! grep -q "^enabled: _test_mcp" <<<"${enable_out}"; then
    echo "[mcp] T13 FAIL: expected 'enabled: _test_mcp' message" >&2
    exit 1
fi
if ! grep -q '"enabled": true' "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json"; then
    echo "[mcp] T13 FAIL: harness-meta.json should report enabled=true" >&2
    exit 1
fi
echo "[mcp] T13 OK"

# --- T14: harness mcp uninstall removes config but preserves data ----------

echo "[mcp] T14: harness mcp uninstall _test_mcp --force"
# Drop a marker into data/ so we can prove preservation.
echo "data marker" >"${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/data/marker.txt"

harness_call mcp uninstall _test_mcp --force >"${TEST_ROOT}/uninstall.log" 2>&1
echo "  | $(grep -E '^uninstalled|^data preserved' "${TEST_ROOT}/uninstall.log" || true)"

if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T14 FAIL: compose.yml still present after uninstall" >&2
    exit 1
fi
if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/harness-meta.json" ]]; then
    echo "[mcp] T14 FAIL: harness-meta.json still present after uninstall" >&2
    exit 1
fi
if [[ ! -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/data/marker.txt" ]]; then
    echo "[mcp] T14 FAIL: data/marker.txt was removed by uninstall" >&2
    exit 1
fi
echo "[mcp] T14 OK"

# --- T15: deprecation alias 'mcp disable --force' still works --------------
#
# After T14 the MCP is uninstalled; reinstall it briefly so we can prove the
# deprecation alias path forwards correctly into the new uninstall verb.

echo "[mcp] T15: deprecation alias 'mcp disable --force' forwards to uninstall"
harness_call mcp install _test_mcp >/dev/null 2>&1
set +e
dep_out=$(harness_call mcp disable _test_mcp --force 2>&1)
dep_rc=$?
set -e
echo "${dep_out}" | sed 's/^/  | /'
if (( dep_rc != 0 )); then
    echo "[mcp] T15 FAIL: deprecation alias should still succeed (rc=${dep_rc})" >&2
    exit 1
fi
if ! grep -q 'DEPRECATED' <<<"${dep_out}"; then
    echo "[mcp] T15 FAIL: deprecation warning missing from stderr" >&2
    exit 1
fi
if [[ -f "${FAKE_INSTALL_ROOT}/state/mcp/_test_mcp/compose.yml" ]]; then
    echo "[mcp] T15 FAIL: deprecation alias did not perform uninstall" >&2
    exit 1
fi
echo "[mcp] T15 OK"

# --- T16: re-running harness start no longer brings up the MCP -------------

echo "[mcp] T16: post-uninstall start drops the MCP service"
harness_call start >"${TEST_ROOT}/start3.log" 2>&1 || {
    echo "[mcp] T16 FAIL: start exited non-zero after uninstall" >&2
    tail -30 "${TEST_ROOT}/start3.log" >&2
    exit 1
}
deadline=$(( $(date +%s) + 30 ))
while true; do
    cid=$(docker ps -q --filter "name=^harness-mcp-test_test_mcp$" 2>/dev/null || true)
    if [[ -z "${cid}" ]]; then break; fi
    if (( $(date +%s) >= deadline )); then
        echo "[mcp] T16 FAIL: test_mcp container still running after uninstall" >&2
        exit 1
    fi
    sleep 2
done
echo "[mcp] T16 OK"

# --- T17: agent side file is cleaned on next launch ------------------------

echo "[mcp] T17: side file disappears when no MCPs are active"
# Re-trigger the side-file write path. Stash image + image-not-found
# again, same trick as T7.
stash_tag=""
if docker image inspect harness-agent:latest >/dev/null 2>&1; then
    stash_tag="harness-agent:mcp-test-stash-$$"
    docker tag harness-agent:latest "${stash_tag}" >/dev/null
    docker rmi harness-agent:latest >/dev/null 2>&1 || true
fi
trap 'restore_image; cleanup' EXIT INT TERM
set +e
harness_call claude -p "ignored" >/dev/null 2>&1
set -e
restore_image
trap cleanup EXIT INT TERM

if [[ -f "${side_file}" ]]; then
    echo "[mcp] T17 FAIL: stale side file should have been removed: ${side_file}" >&2
    cat "${side_file}" >&2
    exit 1
fi
echo "[mcp] T17 OK"

# --- T18: install prints allowed_domains recommendations ---------------------
#
# Add a fixture MCP whose harness-meta.json.template lists allowed_domains.
# `harness mcp install` should PRINT the recommendation but NOT auto-modify
# the allowlist (we then assert the allowlist is unchanged).

echo "[mcp] T18: install prints allowed_domains recommendations"
DOMAINS_REG="${TEST_ROOT}/dom-registry"
mkdir -p "${DOMAINS_REG}/dom_test"
cat >"${DOMAINS_REG}/dom_test/compose.yml" <<'EOF'
services:
  dom_test:
    image: alpine:latest
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
cat >"${DOMAINS_REG}/dom_test/client-config.json" <<'EOF'
{ "mcpServers": { "dom_test": { "type": "sse", "url": "http://dom_test:1/" } } }
EOF
cat >"${DOMAINS_REG}/dom_test/harness-meta.json.template" <<'EOF'
{
  "enabled": true,
  "allowed_domains": [
    "example.com",
    "another.example.org"
  ]
}
EOF

# Snapshot allowlist before so we can prove the recommendation is print-only.
cp "${ALLOWLIST_FILE}" "${ALLOWLIST_FILE}.before-t18"

set +e
dom_out=$(HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
    HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
    HARNESS_REGISTRY_DIR="${DOMAINS_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp install dom_test 2>&1)
dom_rc=$?
set -e
echo "${dom_out}" | sed 's/^/  | /'
if (( dom_rc != 0 )); then
    echo "[mcp] T18 FAIL: install dom_test exited ${dom_rc}" >&2
    exit 1
fi
if ! grep -q 'recommends allowlisting' <<<"${dom_out}"; then
    echo "[mcp] T18 FAIL: install did not print allowed_domains recommendation" >&2
    exit 1
fi
for d in example.com another.example.org; do
    if ! grep -Eq "harness net allow ${d}" <<<"${dom_out}"; then
        echo "[mcp] T18 FAIL: install did not suggest 'harness net allow ${d}'" >&2
        exit 1
    fi
done
# Confirm it did NOT auto-modify the allowlist.
if ! diff -q "${ALLOWLIST_FILE}.before-t18" "${ALLOWLIST_FILE}" >/dev/null; then
    echo "[mcp] T18 FAIL: allowlist was modified by install (must only print)" >&2
    diff -u "${ALLOWLIST_FILE}.before-t18" "${ALLOWLIST_FILE}" >&2 || true
    exit 1
fi
# Cleanup.
HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
HARNESS_REGISTRY_DIR="${DOMAINS_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp uninstall dom_test --force >/dev/null 2>&1 || true
rm -f "${ALLOWLIST_FILE}.before-t18"
echo "[mcp] T18 OK"

# --- T19: empty/no allowed_domains => no recommendation block ---------------
#
# An MCP with empty allowed_domains (the Serena default in B2) must NOT
# print the recommendations section. Same as T18 but with [] in the template.

echo "[mcp] T19: empty allowed_domains prints nothing"
EMPTY_REG="${TEST_ROOT}/empty-domains-registry"
mkdir -p "${EMPTY_REG}/empty_dom"
cat >"${EMPTY_REG}/empty_dom/compose.yml" <<'EOF'
services:
  empty_dom:
    image: alpine:latest
    networks: [harness-net]
    profiles: [mcp]
    command: sh -c 'sleep 9999'
networks:
  harness-net:
EOF
cat >"${EMPTY_REG}/empty_dom/client-config.json" <<'EOF'
{ "mcpServers": { "empty_dom": { "type": "sse", "url": "http://empty_dom:1/" } } }
EOF
cat >"${EMPTY_REG}/empty_dom/harness-meta.json.template" <<'EOF'
{
  "enabled": true,
  "allowed_domains": []
}
EOF

set +e
empty_out=$(HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
    HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
    HARNESS_REGISTRY_DIR="${EMPTY_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp install empty_dom 2>&1)
set -e
if grep -q 'recommends allowlisting' <<<"${empty_out}"; then
    echo "[mcp] T19 FAIL: install printed allowed_domains block for empty array" >&2
    echo "${empty_out}" >&2
    exit 1
fi
HARNESS_PROJECT_NAME="${PROJECT_NAME}" \
HARNESS_INSTALL_ROOT="${FAKE_INSTALL_ROOT}" \
HARNESS_REGISTRY_DIR="${EMPTY_REG}" \
    "${FAKE_INSTALL_ROOT}/harness/harness" mcp uninstall empty_dom --force >/dev/null 2>&1 || true
echo "[mcp] T19 OK"

echo "============================================================"
echo " MCP TEST PASSED"
echo "============================================================"
exit 0
